//! Bulk operations for Appraisal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAppraisalDto;
use crate::application::service::AppraisalService;
use crate::domain::entity::Appraisal;

/// Bulk operation handler for Appraisal entities.
///
/// Wraps `AppraisalService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AppraisalBulkService = GenericBulkService<Appraisal, CreateAppraisalDto, AppraisalService>;

// <<< CUSTOM
// END CUSTOM
