//! Bulk operations for Feedback entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateFeedbackDto;
use crate::application::service::FeedbackService;
use crate::domain::entity::Feedback;

/// Bulk operation handler for Feedback entities.
///
/// Wraps `FeedbackService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type FeedbackBulkService = GenericBulkService<Feedback, CreateFeedbackDto, FeedbackService>;

// <<< CUSTOM
// END CUSTOM
