//! Bulk operations for Goal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateGoalDto;
use crate::application::service::GoalService;
use crate::domain::entity::Goal;

/// Bulk operation handler for Goal entities.
///
/// Wraps `GoalService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type GoalBulkService = GenericBulkService<Goal, CreateGoalDto, GoalService>;

// <<< CUSTOM
// END CUSTOM
