//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod appraisal_bulk;
pub mod appraisal_cycle_bulk;
pub mod feedback_bulk;
pub mod goal_bulk;
pub mod reward_bulk;
pub mod talent_matrix_entry_bulk;

pub use appraisal_bulk::AppraisalBulkService;
pub use appraisal_cycle_bulk::AppraisalCycleBulkService;
pub use feedback_bulk::FeedbackBulkService;
pub use goal_bulk::GoalBulkService;
pub use reward_bulk::RewardBulkService;
pub use talent_matrix_entry_bulk::TalentMatrixEntryBulkService;

// <<< CUSTOM
// END CUSTOM
