//! Bulk operations for TalentMatrixEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTalentMatrixEntryDto;
use crate::application::service::TalentMatrixEntryService;
use crate::domain::entity::TalentMatrixEntry;

/// Bulk operation handler for TalentMatrixEntry entities.
///
/// Wraps `TalentMatrixEntryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TalentMatrixEntryBulkService = GenericBulkService<TalentMatrixEntry, CreateTalentMatrixEntryDto, TalentMatrixEntryService>;

// <<< CUSTOM
// END CUSTOM
