//! AppraisalCycle DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AppraisalCycle;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CycleStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AppraisalCycle
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAppraisalCycleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_type")]
    pub cycle_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_start")]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_end")]
    pub period_end: NaiveDate,
    pub status: CycleStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AppraisalCycle
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAppraisalCycleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_type")]
    pub cycle_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_start")]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_end")]
    pub period_end: NaiveDate,
    pub status: CycleStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AppraisalCycle
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAppraisalCycleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_type")]
    pub cycle_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "period_start")]
    pub period_start: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "period_end")]
    pub period_end: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CycleStatus>,
}

impl PatchAppraisalCycleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some()
            || self.cycle_type.is_some()
            || self.period_start.is_some()
            || self.period_end.is_some()
            || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AppraisalCycle entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalCycleResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub cycle_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period_end: NaiveDate,
    pub status: CycleStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AppraisalCycle entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalCycleListResponseDto {
    /// List of items
    pub items: Vec<AppraisalCycleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AppraisalCycleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<AppraisalCycleResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalCycleSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub cycle_type: Option<String>,
    pub period_start: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AppraisalCycle> for AppraisalCycleResponseDto {
    fn from(entity: AppraisalCycle) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            cycle_type: entity.cycle_type,
            period_start: entity.period_start,
            period_end: entity.period_end,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<AppraisalCycle> for AppraisalCycleSummaryDto {
    fn from(entity: AppraisalCycle) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            cycle_type: entity.cycle_type,
            period_start: entity.period_start,
            created_at,
        }
    }
}

impl From<CreateAppraisalCycleDto> for AppraisalCycle {
    fn from(dto: CreateAppraisalCycleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            cycle_type: dto.cycle_type,
            period_start: dto.period_start,
            period_end: dto.period_end,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AppraisalCycle> for AppraisalCycleResponseDto {
    fn from(entity: &AppraisalCycle) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            cycle_type: entity.cycle_type.clone(),
            period_start: entity.period_start.clone(),
            period_end: entity.period_end.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAppraisalCycleDto> for AppraisalCycle {
    fn from_create_dto(dto: CreateAppraisalCycleDto) -> backbone_core::ServiceResult<Self> {
        Ok(AppraisalCycle::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAppraisalCycleDto> for AppraisalCycle {
    fn apply_update(mut self, dto: UpdateAppraisalCycleDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.cycle_type = dto.cycle_type;
        self.period_start = dto.period_start;
        self.period_end = dto.period_end;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AppraisalCycle here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
