//! Appraisal DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Appraisal;
use crate::domain::entity::AppraisalStatus;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Appraisal
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAppraisalDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "cycle_id")]
    pub cycle_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "reviewer_id")]
    pub reviewer_id: Uuid,
    pub status: AppraisalStatus,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "overall_rating"
    )]
    pub overall_rating: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "submitted_at"
    )]
    pub submitted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Appraisal
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAppraisalDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "cycle_id")]
    pub cycle_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "reviewer_id")]
    pub reviewer_id: Uuid,
    pub status: AppraisalStatus,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "overall_rating"
    )]
    pub overall_rating: Option<Decimal>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "submitted_at"
    )]
    pub submitted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Appraisal
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAppraisalDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "reviewer_id")]
    pub reviewer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<AppraisalStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "overall_rating")]
    pub overall_rating: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "submitted_at")]
    pub submitted_at: Option<DateTime<Utc>>,
}

impl PatchAppraisalDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some()
            || self.cycle_id.is_some()
            || self.reviewer_id.is_some()
            || self.status.is_some()
            || self.overall_rating.is_some()
            || self.submitted_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Appraisal entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub cycle_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub reviewer_id: Uuid,
    pub status: AppraisalStatus,
    pub overall_rating: Option<Decimal>,
    pub submitted_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Appraisal entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalListResponseDto {
    /// List of items
    pub items: Vec<AppraisalResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AppraisalListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AppraisalResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AppraisalSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub cycle_id: Uuid,
    pub reviewer_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Appraisal> for AppraisalResponseDto {
    fn from(entity: Appraisal) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            reviewer_id: entity.reviewer_id,
            status: entity.status,
            overall_rating: entity.overall_rating,
            submitted_at: entity.submitted_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Appraisal> for AppraisalSummaryDto {
    fn from(entity: Appraisal) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            reviewer_id: entity.reviewer_id,
            created_at,
        }
    }
}

impl From<CreateAppraisalDto> for Appraisal {
    fn from(dto: CreateAppraisalDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            cycle_id: dto.cycle_id,
            reviewer_id: dto.reviewer_id,
            status: dto.status,
            overall_rating: dto.overall_rating,
            submitted_at: dto.submitted_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Appraisal> for AppraisalResponseDto {
    fn from(entity: &Appraisal) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            cycle_id: entity.cycle_id.clone(),
            reviewer_id: entity.reviewer_id.clone(),
            status: entity.status.clone(),
            overall_rating: entity.overall_rating.clone(),
            submitted_at: entity.submitted_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAppraisalDto> for Appraisal {
    fn from_create_dto(dto: CreateAppraisalDto) -> backbone_core::ServiceResult<Self> {
        Ok(Appraisal::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAppraisalDto> for Appraisal {
    fn apply_update(mut self, dto: UpdateAppraisalDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.cycle_id = dto.cycle_id;
        self.reviewer_id = dto.reviewer_id;
        self.status = dto.status;
        self.overall_rating = dto.overall_rating;
        self.submitted_at = dto.submitted_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Appraisal here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
