//! Feedback DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Feedback;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::FeedbackRelationship;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Feedback
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateFeedbackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "from_employee_id")]
    pub from_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "to_employee_id")]
    pub to_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub content: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_anonymous")]
    pub is_anonymous: bool,
    pub relationship: FeedbackRelationship,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Feedback
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateFeedbackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "from_employee_id")]
    pub from_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "to_employee_id")]
    pub to_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub content: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_anonymous")]
    pub is_anonymous: bool,
    pub relationship: FeedbackRelationship,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Feedback
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchFeedbackDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_employee_id")]
    pub from_employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_employee_id")]
    pub to_employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_anonymous")]
    pub is_anonymous: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relationship: Option<FeedbackRelationship>,
}

impl PatchFeedbackDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.cycle_id.is_some() || self.from_employee_id.is_some() || self.to_employee_id.is_some() || self.content.is_some() || self.is_anonymous.is_some() || self.relationship.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Feedback entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FeedbackResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub from_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub to_employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub content: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_anonymous: bool,
    pub relationship: FeedbackRelationship,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Feedback entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FeedbackListResponseDto {
    /// List of items
    pub items: Vec<FeedbackResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl FeedbackListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<FeedbackResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FeedbackSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub from_employee_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Feedback> for FeedbackResponseDto {
    fn from(entity: Feedback) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            cycle_id: entity.cycle_id,
            from_employee_id: entity.from_employee_id,
            to_employee_id: entity.to_employee_id,
            content: entity.content,
            is_anonymous: entity.is_anonymous,
            relationship: entity.relationship,
            metadata: entity.metadata,
        }
    }
}

impl From<Feedback> for FeedbackSummaryDto {
    fn from(entity: Feedback) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            cycle_id: entity.cycle_id,
            from_employee_id: entity.from_employee_id,
            created_at,
        }
    }
}

impl From<CreateFeedbackDto> for Feedback {
    fn from(dto: CreateFeedbackDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            cycle_id: dto.cycle_id,
            from_employee_id: dto.from_employee_id,
            to_employee_id: dto.to_employee_id,
            content: dto.content,
            is_anonymous: dto.is_anonymous,
            relationship: dto.relationship,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Feedback> for FeedbackResponseDto {
    fn from(entity: &Feedback) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            cycle_id: entity.cycle_id.clone(),
            from_employee_id: entity.from_employee_id.clone(),
            to_employee_id: entity.to_employee_id.clone(),
            content: entity.content.clone(),
            is_anonymous: entity.is_anonymous.clone(),
            relationship: entity.relationship.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateFeedbackDto> for Feedback {
    fn from_create_dto(dto: CreateFeedbackDto) -> backbone_core::ServiceResult<Self> {
        Ok(Feedback::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateFeedbackDto> for Feedback {
    fn apply_update(mut self, dto: UpdateFeedbackDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.cycle_id = dto.cycle_id;
        self.from_employee_id = dto.from_employee_id;
        self.to_employee_id = dto.to_employee_id;
        self.content = dto.content;
        self.is_anonymous = dto.is_anonymous;
        self.relationship = dto.relationship;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Feedback here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

