//! Goal DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Goal;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GoalStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Goal
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weight: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_goal_id")]
    pub parent_goal_id: Option<Uuid>,
    pub status: GoalStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Goal
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weight: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_goal_id")]
    pub parent_goal_id: Option<Uuid>,
    pub status: GoalStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Goal
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGoalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weight: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_goal_id")]
    pub parent_goal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<GoalStatus>,
}

impl PatchGoalDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.cycle_id.is_some() || self.title.is_some() || self.description.is_some() || self.weight.is_some() || self.progress.is_some() || self.parent_goal_id.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Goal entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoalResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub description: Option<String>,
    pub weight: Option<Decimal>,
    pub progress: Option<Decimal>,
    pub parent_goal_id: Option<Uuid>,
    pub status: GoalStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Goal entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoalListResponseDto {
    /// List of items
    pub items: Vec<GoalResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GoalListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GoalResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoalSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Goal> for GoalResponseDto {
    fn from(entity: Goal) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            title: entity.title,
            description: entity.description,
            weight: entity.weight,
            progress: entity.progress,
            parent_goal_id: entity.parent_goal_id,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Goal> for GoalSummaryDto {
    fn from(entity: Goal) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            created_at,
        }
    }
}

impl From<CreateGoalDto> for Goal {
    fn from(dto: CreateGoalDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            cycle_id: dto.cycle_id,
            title: dto.title,
            description: dto.description,
            weight: dto.weight,
            progress: dto.progress,
            parent_goal_id: dto.parent_goal_id,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Goal> for GoalResponseDto {
    fn from(entity: &Goal) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            cycle_id: entity.cycle_id.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            weight: entity.weight.clone(),
            progress: entity.progress.clone(),
            parent_goal_id: entity.parent_goal_id.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGoalDto> for Goal {
    fn from_create_dto(dto: CreateGoalDto) -> backbone_core::ServiceResult<Self> {
        Ok(Goal::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGoalDto> for Goal {
    fn apply_update(mut self, dto: UpdateGoalDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.cycle_id = dto.cycle_id;
        self.title = dto.title;
        self.description = dto.description;
        self.weight = dto.weight;
        self.progress = dto.progress;
        self.parent_goal_id = dto.parent_goal_id;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Goal here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

