//! Reward DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Reward;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::RewardType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Reward
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRewardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[serde(alias = "reward_type")]
    pub reward_type: RewardType,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "awarded_by")]
    pub awarded_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "awarded_at")]
    pub awarded_at: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payroll_component_id")]
    pub payroll_component_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Reward
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRewardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[serde(alias = "reward_type")]
    pub reward_type: RewardType,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "awarded_by")]
    pub awarded_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "awarded_at")]
    pub awarded_at: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payroll_component_id")]
    pub payroll_component_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Reward
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRewardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reward_type")]
    pub reward_type: Option<RewardType>,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "awarded_by")]
    pub awarded_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "awarded_at")]
    pub awarded_at: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "payroll_component_id")]
    pub payroll_component_id: Option<Uuid>,
}

impl PatchRewardDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.cycle_id.is_some() || self.reward_type.is_some() || self.title.is_some() || self.description.is_some() || self.amount.is_some() || self.awarded_by.is_some() || self.awarded_at.is_some() || self.payroll_component_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Reward entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RewardResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub reward_type: RewardType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub description: Option<String>,
    pub amount: Option<Decimal>,
    pub awarded_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub awarded_at: NaiveDate,
    pub payroll_component_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Reward entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RewardListResponseDto {
    /// List of items
    pub items: Vec<RewardResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RewardListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RewardResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RewardSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Reward> for RewardResponseDto {
    fn from(entity: Reward) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            reward_type: entity.reward_type,
            title: entity.title,
            description: entity.description,
            amount: entity.amount,
            awarded_by: entity.awarded_by,
            awarded_at: entity.awarded_at,
            payroll_component_id: entity.payroll_component_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Reward> for RewardSummaryDto {
    fn from(entity: Reward) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            created_at,
        }
    }
}

impl From<CreateRewardDto> for Reward {
    fn from(dto: CreateRewardDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            cycle_id: dto.cycle_id,
            reward_type: dto.reward_type,
            title: dto.title,
            description: dto.description,
            amount: dto.amount,
            awarded_by: dto.awarded_by,
            awarded_at: dto.awarded_at,
            payroll_component_id: dto.payroll_component_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Reward> for RewardResponseDto {
    fn from(entity: &Reward) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            cycle_id: entity.cycle_id.clone(),
            reward_type: entity.reward_type.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            amount: entity.amount.clone(),
            awarded_by: entity.awarded_by.clone(),
            awarded_at: entity.awarded_at.clone(),
            payroll_component_id: entity.payroll_component_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRewardDto> for Reward {
    fn from_create_dto(dto: CreateRewardDto) -> backbone_core::ServiceResult<Self> {
        Ok(Reward::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRewardDto> for Reward {
    fn apply_update(mut self, dto: UpdateRewardDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.cycle_id = dto.cycle_id;
        self.reward_type = dto.reward_type;
        self.title = dto.title;
        self.description = dto.description;
        self.amount = dto.amount;
        self.awarded_by = dto.awarded_by;
        self.awarded_at = dto.awarded_at;
        self.payroll_component_id = dto.payroll_component_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Reward here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

