//! TalentMatrixEntry DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TalentMatrixEntry;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TalentMatrixEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTalentMatrixEntryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "cycle_id")]
    pub cycle_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "performance_score")]
    pub performance_score: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "potential_score")]
    pub potential_score: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "box_label")]
    pub box_label: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TalentMatrixEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTalentMatrixEntryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "cycle_id")]
    pub cycle_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "performance_score")]
    pub performance_score: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "potential_score")]
    pub potential_score: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "box_label")]
    pub box_label: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TalentMatrixEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTalentMatrixEntryDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cycle_id")]
    pub cycle_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "performance_score")]
    pub performance_score: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "potential_score")]
    pub potential_score: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "box_label")]
    pub box_label: Option<String>,
}

impl PatchTalentMatrixEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some()
            || self.cycle_id.is_some()
            || self.performance_score.is_some()
            || self.potential_score.is_some()
            || self.box_label.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TalentMatrixEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TalentMatrixEntryResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub cycle_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub performance_score: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub potential_score: i32,
    pub box_label: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TalentMatrixEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TalentMatrixEntryListResponseDto {
    /// List of items
    pub items: Vec<TalentMatrixEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TalentMatrixEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<TalentMatrixEntryResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TalentMatrixEntrySummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub cycle_id: Uuid,
    pub performance_score: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TalentMatrixEntry> for TalentMatrixEntryResponseDto {
    fn from(entity: TalentMatrixEntry) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            performance_score: entity.performance_score,
            potential_score: entity.potential_score,
            box_label: entity.box_label,
            metadata: entity.metadata,
        }
    }
}

impl From<TalentMatrixEntry> for TalentMatrixEntrySummaryDto {
    fn from(entity: TalentMatrixEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            cycle_id: entity.cycle_id,
            performance_score: entity.performance_score,
            created_at,
        }
    }
}

impl From<CreateTalentMatrixEntryDto> for TalentMatrixEntry {
    fn from(dto: CreateTalentMatrixEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            cycle_id: dto.cycle_id,
            performance_score: dto.performance_score,
            potential_score: dto.potential_score,
            box_label: dto.box_label,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TalentMatrixEntry> for TalentMatrixEntryResponseDto {
    fn from(entity: &TalentMatrixEntry) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            cycle_id: entity.cycle_id.clone(),
            performance_score: entity.performance_score.clone(),
            potential_score: entity.potential_score.clone(),
            box_label: entity.box_label.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTalentMatrixEntryDto> for TalentMatrixEntry {
    fn from_create_dto(dto: CreateTalentMatrixEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(TalentMatrixEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTalentMatrixEntryDto> for TalentMatrixEntry {
    fn apply_update(
        mut self,
        dto: UpdateTalentMatrixEntryDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.cycle_id = dto.cycle_id;
        self.performance_score = dto.performance_score;
        self.potential_score = dto.potential_score;
        self.box_label = dto.box_label;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TalentMatrixEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
