//! Specifications for Feedback aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Entity-specific predicate structs implementing `backbone_core::Specification`.
//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.

use crate::domain::entity::Feedback;
use backbone_core::Specification;

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification};

// ─── Entity-specific predicates ──────────────────────────────────────────────
//
// Add entity-specific predicate structs below.
// Each predicate implements `Specification<Feedback>` and can be combined
// using `.and()`, `.or()`, `.not()` from the trait.
//
// Example:
//   let spec = ActiveSpec.and(VerifiedSpec);
//   if spec.is_satisfied_by(&entity) { ... }

// <<< CUSTOM
// Add predicate structs here. Example:
//
// pub struct ActiveFeedbackSpec;
// impl Specification<Feedback> for ActiveFeedbackSpec {
//     fn is_satisfied_by(&self, e: &Feedback) -> bool {
//         // e.is_active
//         todo!()
//     }
// }
// END CUSTOM
