//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification, Specification};

pub mod appraisal_cycle_specification;
pub mod appraisal_specification;
pub mod feedback_specification;
pub mod goal_specification;
pub mod reward_specification;
pub mod talent_matrix_entry_specification;

// <<< CUSTOM
// END CUSTOM
