//! Domain policy for Appraisal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Appraisal;

/// Domain policy for Appraisal — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Appraisal>` in the `// <<< CUSTOM` zone.
pub type AppraisalDomainPolicy = PermitAllPolicy<Appraisal>;

// <<< CUSTOM
// END CUSTOM
