//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod appraisal_domain_policy;
pub mod appraisal_cycle_domain_policy;
pub mod feedback_domain_policy;
pub mod goal_domain_policy;
pub mod reward_domain_policy;
pub mod talent_matrix_entry_domain_policy;

pub use appraisal_domain_policy::AppraisalDomainPolicy;
pub use appraisal_cycle_domain_policy::AppraisalCycleDomainPolicy;
pub use feedback_domain_policy::FeedbackDomainPolicy;
pub use goal_domain_policy::GoalDomainPolicy;
pub use reward_domain_policy::RewardDomainPolicy;
pub use talent_matrix_entry_domain_policy::TalentMatrixEntryDomainPolicy;

// <<< CUSTOM
// END CUSTOM
