//! Domain policy for Reward aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Reward;

/// Domain policy for Reward — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Reward>` in the `// <<< CUSTOM` zone.
pub type RewardDomainPolicy = PermitAllPolicy<Reward>;

// <<< CUSTOM
// END CUSTOM
