//! Application service for Appraisal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `appraisal_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAppraisalDto, UpdateAppraisalDto};
use crate::domain::entity::Appraisal;
use crate::infrastructure::persistence::AppraisalRepository;

/// Application service for Appraisal entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `appraisal_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AppraisalServiceCustom {
///     inner: Arc<AppraisalService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AppraisalService = GenericCrudService<
    Appraisal,
    CreateAppraisalDto,
    UpdateAppraisalDto,
    AppraisalRepository,
>;

// <<< CUSTOM
// END CUSTOM
