//! Application service for AppraisalCycle entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `appraisal_cycle_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAppraisalCycleDto, UpdateAppraisalCycleDto};
use crate::domain::entity::AppraisalCycle;
use crate::infrastructure::persistence::AppraisalCycleRepository;

/// Application service for AppraisalCycle entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `appraisal_cycle_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AppraisalCycleServiceCustom {
///     inner: Arc<AppraisalCycleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AppraisalCycleService = GenericCrudService<
    AppraisalCycle,
    CreateAppraisalCycleDto,
    UpdateAppraisalCycleDto,
    AppraisalCycleRepository,
>;

// <<< CUSTOM
// END CUSTOM
