//! Application service for Goal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `goal_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateGoalDto, UpdateGoalDto};
use crate::domain::entity::Goal;
use crate::infrastructure::persistence::GoalRepository;

/// Application service for Goal entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `goal_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct GoalServiceCustom {
///     inner: Arc<GoalService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type GoalService = GenericCrudService<
    Goal,
    CreateGoalDto,
    UpdateGoalDto,
    GoalRepository,
>;

// <<< CUSTOM
// END CUSTOM
