//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod appraisal_cycle_service;
pub mod appraisal_service;
pub mod feedback_service;
pub mod goal_service;
pub mod reward_service;
pub mod talent_matrix_entry_service;

// <<< CUSTOM
// The validated write path: cycles, goals, appraisals with the ONE
// finalised predicate.
pub mod performance_write_service;
pub mod performance_events;
// END CUSTOM

pub use appraisal_cycle_service::AppraisalCycleService;
pub use appraisal_service::AppraisalService;
pub use feedback_service::FeedbackService;
pub use goal_service::GoalService;
pub use reward_service::RewardService;
pub use talent_matrix_entry_service::TalentMatrixEntryService;
// <<< CUSTOM
pub use performance_write_service::{
    NewAppraisal, NewCycle, NewGoal, PerformanceError, PerformanceWriteService,
};
pub use performance_events::{LoggingSink as PerformanceLoggingSink, PerformanceEvent, PerformanceEventSink};
// END CUSTOM
