//! Application service for TalentMatrixEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `talent_matrix_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::TalentMatrixEntry;
use crate::infrastructure::persistence::TalentMatrixEntryRepository;
use crate::presentation::dto::{CreateTalentMatrixEntryDto, UpdateTalentMatrixEntryDto};

/// Application service for TalentMatrixEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `talent_matrix_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TalentMatrixEntryServiceCustom {
///     inner: Arc<TalentMatrixEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TalentMatrixEntryService = GenericCrudService<
    TalentMatrixEntry,
    CreateTalentMatrixEntryDto,
    UpdateTalentMatrixEntryDto,
    TalentMatrixEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
