-- Appraisal Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the performance.appraisals table.
-- Customize this file to add your initial data.

-- INSERT INTO performance.appraisals (
--     id,
--     company_id,
--     employee_id,
--     cycle_id,
--     reviewer_id,
--     status,
--     overall_rating,
--     submitted_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO performance.appraisals (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

