-- AppraisalCycle Seed Data
-- Generated by metaphor-schema
--
-- SEED: none — performance data is tenant content, never global reference data.
-- Customize this file to add your initial data.

-- INSERT INTO performance.appraisal_cycles (
--     id,
--     company_id,
--     name,
--     cycle_type,
--     period_start,
--     period_end,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO performance.appraisal_cycles (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

