-- Feedback Seed Data
-- Generated by metaphor-schema
--
-- SEED: none — performance data is tenant content, never global reference data.
-- Customize this file to add your initial data.

-- INSERT INTO performance.performance_feedback (
--     id,
--     company_id,
--     cycle_id,
--     from_employee_id,
--     to_employee_id,
--     content,
--     is_anonymous,
--     relationship,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO performance.performance_feedback (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

