-- Goal Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the performance.goals table.
-- Customize this file to add your initial data.

-- INSERT INTO performance.goals (
--     id,
--     company_id,
--     employee_id,
--     cycle_id,
--     title,
--     description,
--     weight,
--     progress,
--     parent_goal_id,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO performance.goals (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

