-- Reward Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the performance.rewards table.
-- Customize this file to add your initial data.

-- INSERT INTO performance.rewards (
--     id,
--     company_id,
--     employee_id,
--     cycle_id,
--     reward_type,
--     title,
--     description,
--     amount,
--     awarded_by,
--     awarded_at,
--     payroll_component_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO performance.rewards (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

