-- TalentMatrixEntry Seed Data
-- Generated by metaphor-schema
--
-- SEED: none — performance data is tenant content, never global reference data.
-- Customize this file to add your initial data.

-- INSERT INTO performance.talent_matrix_entries (
--     id,
--     company_id,
--     employee_id,
--     cycle_id,
--     performance_score,
--     potential_score,
--     box,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO performance.talent_matrix_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

