-- Migration: Create appraisals table
-- Generated by metaphor-schema

-- Create appraisal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appraisal_status') THEN
        CREATE TYPE appraisal_status AS ENUM ('draft', 'self_review', 'submitted', 'calibrated', 'finalized');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.appraisals (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    cycle_id UUID NOT NULL,
    reviewer_id UUID NOT NULL,
    status appraisal_status NOT NULL DEFAULT 'draft',
    overall_rating NUMERIC(3, 1) CHECK (overall_rating >= 0),
    submitted_at TIMESTAMPTZ,
    self_review JSONB,
    manager_review JSONB,
    rated_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_appraisals_company_id_employee_id_cycle_id ON performance.appraisals (company_id, employee_id, cycle_id);

CREATE INDEX IF NOT EXISTS idx_appraisals_cycle_id ON performance.appraisals (cycle_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_appraisals_metadata_gin ON performance.appraisals USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_appraisals_metadata_deleted_at ON performance.appraisals ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_appraisals_metadata_created_at ON performance.appraisals ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_appraisals_metadata_updated_at ON performance.appraisals ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.appraisals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS appraisals_insert_audit ON performance.appraisals;
CREATE TRIGGER appraisals_insert_audit BEFORE INSERT ON performance.appraisals
    FOR EACH ROW EXECUTE FUNCTION performance.appraisals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS appraisals_update_audit ON performance.appraisals;
CREATE TRIGGER appraisals_update_audit BEFORE UPDATE ON performance.appraisals
    FOR EACH ROW EXECUTE FUNCTION performance.appraisals_audit_timestamp();
