-- Migration: Create appraisal_cycles table
-- Generated by metaphor-schema

-- Create cycle_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cycle_status') THEN
        CREATE TYPE cycle_status AS ENUM ('draft', 'open', 'calibration', 'closed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.appraisal_cycles (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    cycle_type TEXT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status cycle_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_appraisal_cycles_company_id_status ON performance.appraisal_cycles (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_appraisal_cycles_metadata_gin ON performance.appraisal_cycles USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_appraisal_cycles_metadata_deleted_at ON performance.appraisal_cycles ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_appraisal_cycles_metadata_created_at ON performance.appraisal_cycles ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_appraisal_cycles_metadata_updated_at ON performance.appraisal_cycles ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.appraisal_cycles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS appraisal_cycles_insert_audit ON performance.appraisal_cycles;
CREATE TRIGGER appraisal_cycles_insert_audit BEFORE INSERT ON performance.appraisal_cycles
    FOR EACH ROW EXECUTE FUNCTION performance.appraisal_cycles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS appraisal_cycles_update_audit ON performance.appraisal_cycles;
CREATE TRIGGER appraisal_cycles_update_audit BEFORE UPDATE ON performance.appraisal_cycles
    FOR EACH ROW EXECUTE FUNCTION performance.appraisal_cycles_audit_timestamp();
