-- Company RLS fence for performance module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for performance.appraisals
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.appraisals ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.appraisals FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS appraisals_company_isolation ON performance.appraisals;
CREATE POLICY appraisals_company_isolation ON performance.appraisals
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for performance.appraisal_cycles
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.appraisal_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.appraisal_cycles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS appraisal_cycles_company_isolation ON performance.appraisal_cycles;
CREATE POLICY appraisal_cycles_company_isolation ON performance.appraisal_cycles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for performance.performance_feedback
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.performance_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.performance_feedback FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS performance_feedback_company_isolation ON performance.performance_feedback;
CREATE POLICY performance_feedback_company_isolation ON performance.performance_feedback
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for performance.goals
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.goals FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS goals_company_isolation ON performance.goals;
CREATE POLICY goals_company_isolation ON performance.goals
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for performance.rewards
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.rewards FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rewards_company_isolation ON performance.rewards;
CREATE POLICY rewards_company_isolation ON performance.rewards
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for performance.talent_matrix_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE performance.talent_matrix_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance.talent_matrix_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS talent_matrix_entries_company_isolation ON performance.talent_matrix_entries;
CREATE POLICY talent_matrix_entries_company_isolation ON performance.talent_matrix_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

