-- Migration: Create talent_matrix_entries table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.talent_matrix_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    cycle_id UUID NOT NULL,
    performance_score INTEGER NOT NULL CHECK (performance_score >= 0),
    potential_score INTEGER NOT NULL CHECK (potential_score >= 0),
    box TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_talent_matrix_entries_company_id_employee_id_cycle_id ON performance.talent_matrix_entries (company_id, employee_id, cycle_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_talent_matrix_entries_metadata_gin ON performance.talent_matrix_entries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_talent_matrix_entries_metadata_deleted_at ON performance.talent_matrix_entries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_talent_matrix_entries_metadata_created_at ON performance.talent_matrix_entries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_talent_matrix_entries_metadata_updated_at ON performance.talent_matrix_entries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.talent_matrix_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS talent_matrix_entries_insert_audit ON performance.talent_matrix_entries;
CREATE TRIGGER talent_matrix_entries_insert_audit BEFORE INSERT ON performance.talent_matrix_entries
    FOR EACH ROW EXECUTE FUNCTION performance.talent_matrix_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS talent_matrix_entries_update_audit ON performance.talent_matrix_entries;
CREATE TRIGGER talent_matrix_entries_update_audit BEFORE UPDATE ON performance.talent_matrix_entries
    FOR EACH ROW EXECUTE FUNCTION performance.talent_matrix_entries_audit_timestamp();
