-- Enum types for performance module
-- Generated by metaphor-schema

-- Create appraisal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appraisal_status') THEN
        CREATE TYPE appraisal_status AS ENUM ('draft', 'self_review', 'submitted', 'calibrated', 'finalized');
    END IF;
END
$$;

-- Create cycle_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cycle_status') THEN
        CREATE TYPE cycle_status AS ENUM ('draft', 'open', 'calibration', 'closed');
    END IF;
END
$$;

-- Create feedback_relationship enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'feedback_relationship') THEN
        CREATE TYPE feedback_relationship AS ENUM ('peer', 'manager', 'direct_report', 'cross_functional');
    END IF;
END
$$;

-- Create goal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_status') THEN
        CREATE TYPE goal_status AS ENUM ('draft', 'active', 'achieved', 'missed', 'cancelled');
    END IF;
END
$$;

-- Create reward_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reward_type') THEN
        CREATE TYPE reward_type AS ENUM ('recognition', 'bonus', 'gift', 'leave_credit', 'certificate');
    END IF;
END
$$;

