-- Audit Triggers Migration for performance module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Appraisal (performance.appraisals)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.appraisals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS appraisals_insert_audit ON performance.appraisals;
CREATE TRIGGER appraisals_insert_audit BEFORE INSERT ON performance.appraisals
    FOR EACH ROW EXECUTE FUNCTION performance.appraisals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS appraisals_update_audit ON performance.appraisals;
CREATE TRIGGER appraisals_update_audit BEFORE UPDATE ON performance.appraisals
    FOR EACH ROW EXECUTE FUNCTION performance.appraisals_audit_timestamp();

-- ==============================================================================
-- Table: AppraisalCycle (performance.appraisal_cycles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.appraisal_cycles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS appraisal_cycles_insert_audit ON performance.appraisal_cycles;
CREATE TRIGGER appraisal_cycles_insert_audit BEFORE INSERT ON performance.appraisal_cycles
    FOR EACH ROW EXECUTE FUNCTION performance.appraisal_cycles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS appraisal_cycles_update_audit ON performance.appraisal_cycles;
CREATE TRIGGER appraisal_cycles_update_audit BEFORE UPDATE ON performance.appraisal_cycles
    FOR EACH ROW EXECUTE FUNCTION performance.appraisal_cycles_audit_timestamp();

-- ==============================================================================
-- Table: Feedback (performance.performance_feedback)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.performance_feedback_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS performance_feedback_insert_audit ON performance.performance_feedback;
CREATE TRIGGER performance_feedback_insert_audit BEFORE INSERT ON performance.performance_feedback
    FOR EACH ROW EXECUTE FUNCTION performance.performance_feedback_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS performance_feedback_update_audit ON performance.performance_feedback;
CREATE TRIGGER performance_feedback_update_audit BEFORE UPDATE ON performance.performance_feedback
    FOR EACH ROW EXECUTE FUNCTION performance.performance_feedback_audit_timestamp();

-- ==============================================================================
-- Table: Goal (performance.goals)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.goals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS goals_insert_audit ON performance.goals;
CREATE TRIGGER goals_insert_audit BEFORE INSERT ON performance.goals
    FOR EACH ROW EXECUTE FUNCTION performance.goals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS goals_update_audit ON performance.goals;
CREATE TRIGGER goals_update_audit BEFORE UPDATE ON performance.goals
    FOR EACH ROW EXECUTE FUNCTION performance.goals_audit_timestamp();

-- ==============================================================================
-- Table: Reward (performance.rewards)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.rewards_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rewards_insert_audit ON performance.rewards;
CREATE TRIGGER rewards_insert_audit BEFORE INSERT ON performance.rewards
    FOR EACH ROW EXECUTE FUNCTION performance.rewards_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rewards_update_audit ON performance.rewards;
CREATE TRIGGER rewards_update_audit BEFORE UPDATE ON performance.rewards
    FOR EACH ROW EXECUTE FUNCTION performance.rewards_audit_timestamp();

-- ==============================================================================
-- Table: TalentMatrixEntry (performance.talent_matrix_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION performance.talent_matrix_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS talent_matrix_entries_insert_audit ON performance.talent_matrix_entries;
CREATE TRIGGER talent_matrix_entries_insert_audit BEFORE INSERT ON performance.talent_matrix_entries
    FOR EACH ROW EXECUTE FUNCTION performance.talent_matrix_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS talent_matrix_entries_update_audit ON performance.talent_matrix_entries;
CREATE TRIGGER talent_matrix_entries_update_audit BEFORE UPDATE ON performance.talent_matrix_entries
    FOR EACH ROW EXECUTE FUNCTION performance.talent_matrix_entries_audit_timestamp();

