-- Migration: Create rewards table
-- Generated by metaphor-schema

-- Create reward_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reward_type') THEN
        CREATE TYPE reward_type AS ENUM ('recognition', 'bonus', 'gift', 'leave_credit', 'certificate');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.rewards (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    cycle_id UUID,
    reward_type reward_type NOT NULL DEFAULT 'recognition',
    title TEXT NOT NULL,
    description TEXT,
    amount NUMERIC(18, 2) CHECK (amount >= 0),
    awarded_by UUID,
    awarded_at DATE NOT NULL,
    payroll_component_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_rewards_company_id_employee_id_awarded_at ON performance.rewards (company_id, employee_id, awarded_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_rewards_metadata_gin ON performance.rewards USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_rewards_metadata_deleted_at ON performance.rewards ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_rewards_metadata_created_at ON performance.rewards ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_rewards_metadata_updated_at ON performance.rewards ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.rewards_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rewards_insert_audit ON performance.rewards;
CREATE TRIGGER rewards_insert_audit BEFORE INSERT ON performance.rewards
    FOR EACH ROW EXECUTE FUNCTION performance.rewards_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rewards_update_audit ON performance.rewards;
CREATE TRIGGER rewards_update_audit BEFORE UPDATE ON performance.rewards
    FOR EACH ROW EXECUTE FUNCTION performance.rewards_audit_timestamp();
