-- Migration: Create performance_feedback table
-- Generated by metaphor-schema

-- Create feedback_relationship enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'feedback_relationship') THEN
        CREATE TYPE feedback_relationship AS ENUM ('peer', 'manager', 'direct_report', 'cross_functional');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.performance_feedback (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    cycle_id UUID,
    from_employee_id UUID NOT NULL,
    to_employee_id UUID NOT NULL,
    content TEXT NOT NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
    relationship feedback_relationship NOT NULL DEFAULT 'peer',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_performance_feedback_company_id_to_employee_id ON performance.performance_feedback (company_id, to_employee_id);

CREATE INDEX IF NOT EXISTS idx_performance_feedback_cycle_id ON performance.performance_feedback (cycle_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_performance_feedback_metadata_gin ON performance.performance_feedback USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_performance_feedback_metadata_deleted_at ON performance.performance_feedback ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_performance_feedback_metadata_created_at ON performance.performance_feedback ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_performance_feedback_metadata_updated_at ON performance.performance_feedback ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.performance_feedback_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS performance_feedback_insert_audit ON performance.performance_feedback;
CREATE TRIGGER performance_feedback_insert_audit BEFORE INSERT ON performance.performance_feedback
    FOR EACH ROW EXECUTE FUNCTION performance.performance_feedback_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS performance_feedback_update_audit ON performance.performance_feedback;
CREATE TRIGGER performance_feedback_update_audit BEFORE UPDATE ON performance.performance_feedback
    FOR EACH ROW EXECUTE FUNCTION performance.performance_feedback_audit_timestamp();
