-- Migration: Create goals table
-- Generated by metaphor-schema

-- Create goal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_status') THEN
        CREATE TYPE goal_status AS ENUM ('draft', 'active', 'achieved', 'missed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS performance;

CREATE TABLE IF NOT EXISTS performance.goals (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    cycle_id UUID,
    title TEXT NOT NULL,
    description TEXT,
    weight NUMERIC(5, 2) CHECK (weight >= 0),
    progress NUMERIC(5, 2) CHECK (progress >= 0),
    parent_goal_id UUID,
    status goal_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_goals_company_id_employee_id ON performance.goals (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_goals_cycle_id ON performance.goals (cycle_id);

CREATE INDEX IF NOT EXISTS idx_goals_parent_goal_id ON performance.goals (parent_goal_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_goals_metadata_gin ON performance.goals USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_goals_metadata_deleted_at ON performance.goals ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_goals_metadata_created_at ON performance.goals ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_goals_metadata_updated_at ON performance.goals ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION performance.goals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS goals_insert_audit ON performance.goals;
CREATE TRIGGER goals_insert_audit BEFORE INSERT ON performance.goals
    FOR EACH ROW EXECUTE FUNCTION performance.goals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS goals_update_audit ON performance.goals;
CREATE TRIGGER goals_update_audit BEFORE UPDATE ON performance.goals
    FOR EACH ROW EXECUTE FUNCTION performance.goals_audit_timestamp();
