//! Event handler trait for AppraisalCycle events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AppraisalCycleEvent;

/// Event handler for AppraisalCycle events.
/// Implement this trait to react to AppraisalCycle lifecycle events.
pub trait AppraisalCycleEventHandler: EventHandler<AppraisalCycleEvent> {}
