//! Domain events for AppraisalCycle entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AppraisalCycle;

/// Domain events for AppraisalCycle — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AppraisalCycle>)` variant.
pub type AppraisalCycleEvent = CrudEvent<AppraisalCycle>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AppraisalCycle events.
pub type AppraisalCycleEventPublisher = Arc<dyn CrudEventPublisher<AppraisalCycle> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAppraisalCycleEventPublisher = NoOpCrudEventPublisher<AppraisalCycle>;
