//! Domain events for Appraisal entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Appraisal;

/// Domain events for Appraisal — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Appraisal>)` variant.
pub type AppraisalEvent = CrudEvent<Appraisal>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Appraisal events.
pub type AppraisalEventPublisher = Arc<dyn CrudEventPublisher<Appraisal> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAppraisalEventPublisher = NoOpCrudEventPublisher<Appraisal>;
