//! Event handler trait for Appraisal events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AppraisalEvent;

/// Event handler for Appraisal events.
/// Implement this trait to react to Appraisal lifecycle events.
pub trait AppraisalEventHandler: EventHandler<AppraisalEvent> {}
