//! Event handler trait for Feedback events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::FeedbackEvent;
use backbone_messaging::EventHandler;

/// Event handler for Feedback events.
/// Implement this trait to react to Feedback lifecycle events.
pub trait FeedbackEventHandler: EventHandler<FeedbackEvent> {}
