//! Event handler trait for Feedback events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::FeedbackEvent;

/// Event handler for Feedback events.
/// Implement this trait to react to Feedback lifecycle events.
pub trait FeedbackEventHandler: EventHandler<FeedbackEvent> {}
