//! Domain events for Feedback entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::Feedback;
use backbone_messaging::CrudEvent;

/// Domain events for Feedback — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Feedback>)` variant.
pub type FeedbackEvent = CrudEvent<Feedback>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Feedback events.
pub type FeedbackEventPublisher = Arc<dyn CrudEventPublisher<Feedback> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFeedbackEventPublisher = NoOpCrudEventPublisher<Feedback>;
