//! Event handler trait for Goal events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::GoalEvent;

/// Event handler for Goal events.
/// Implement this trait to react to Goal lifecycle events.
pub trait GoalEventHandler: EventHandler<GoalEvent> {}
