//! Event handler trait for Goal events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::GoalEvent;
use backbone_messaging::EventHandler;

/// Event handler for Goal events.
/// Implement this trait to react to Goal lifecycle events.
pub trait GoalEventHandler: EventHandler<GoalEvent> {}
