//! Domain events for Goal entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::Goal;
use backbone_messaging::CrudEvent;

/// Domain events for Goal — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Goal>)` variant.
pub type GoalEvent = CrudEvent<Goal>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Goal events.
pub type GoalEventPublisher = Arc<dyn CrudEventPublisher<Goal> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopGoalEventPublisher = NoOpCrudEventPublisher<Goal>;
