//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod appraisal_events;
pub mod appraisal_event_handlers;
pub mod appraisal_cycle_events;
pub mod appraisal_cycle_event_handlers;
pub mod feedback_events;
pub mod feedback_event_handlers;
pub mod goal_events;
pub mod goal_event_handlers;
pub mod reward_events;
pub mod reward_event_handlers;
pub mod talent_matrix_entry_events;
pub mod talent_matrix_entry_event_handlers;

pub use appraisal_events::{AppraisalEvent, AppraisalEventPublisher, NoopAppraisalEventPublisher};
pub use appraisal_event_handlers::AppraisalEventHandler;
pub use appraisal_cycle_events::{AppraisalCycleEvent, AppraisalCycleEventPublisher, NoopAppraisalCycleEventPublisher};
pub use appraisal_cycle_event_handlers::AppraisalCycleEventHandler;
pub use feedback_events::{FeedbackEvent, FeedbackEventPublisher, NoopFeedbackEventPublisher};
pub use feedback_event_handlers::FeedbackEventHandler;
pub use goal_events::{GoalEvent, GoalEventPublisher, NoopGoalEventPublisher};
pub use goal_event_handlers::GoalEventHandler;
pub use reward_events::{RewardEvent, RewardEventPublisher, NoopRewardEventPublisher};
pub use reward_event_handlers::RewardEventHandler;
pub use talent_matrix_entry_events::{TalentMatrixEntryEvent, TalentMatrixEntryEventPublisher, NoopTalentMatrixEntryEventPublisher};
pub use talent_matrix_entry_event_handlers::TalentMatrixEntryEventHandler;

// <<< CUSTOM
// END CUSTOM
