//! Event handler trait for Reward events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::RewardEvent;
use backbone_messaging::EventHandler;

/// Event handler for Reward events.
/// Implement this trait to react to Reward lifecycle events.
pub trait RewardEventHandler: EventHandler<RewardEvent> {}
