//! Event handler trait for Reward events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RewardEvent;

/// Event handler for Reward events.
/// Implement this trait to react to Reward lifecycle events.
pub trait RewardEventHandler: EventHandler<RewardEvent> {}
