//! Domain events for Reward entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Reward;

/// Domain events for Reward — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Reward>)` variant.
pub type RewardEvent = CrudEvent<Reward>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Reward events.
pub type RewardEventPublisher = Arc<dyn CrudEventPublisher<Reward> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRewardEventPublisher = NoOpCrudEventPublisher<Reward>;
