//! Domain events for TalentMatrixEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::TalentMatrixEntry;
use backbone_messaging::CrudEvent;

/// Domain events for TalentMatrixEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TalentMatrixEntry>)` variant.
pub type TalentMatrixEntryEvent = CrudEvent<TalentMatrixEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TalentMatrixEntry events.
pub type TalentMatrixEntryEventPublisher =
    Arc<dyn CrudEventPublisher<TalentMatrixEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTalentMatrixEntryEventPublisher = NoOpCrudEventPublisher<TalentMatrixEntry>;
