//! Event handler trait for TalentMatrixEntry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::TalentMatrixEntryEvent;
use backbone_messaging::EventHandler;

/// Event handler for TalentMatrixEntry events.
/// Implement this trait to react to TalentMatrixEntry lifecycle events.
pub trait TalentMatrixEntryEventHandler: EventHandler<TalentMatrixEntryEvent> {}
