//! AppraisalCycle seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AppraisalCycle data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// APPRAISALCYCLE SEEDER
// ============================================================================

/// Seeder for appraisal_cycle
pub struct SeedAppraisalCycleSeeder;

impl SeedAppraisalCycleSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAppraisalCycleSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAppraisalCycleSeeder {
    fn name(&self) -> &'static str {
        "SeedAppraisalCycleSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if performance.appraisal_cycles table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM performance.appraisal_cycles")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/appraisal_cycle_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM performance.appraisal_cycles")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

