//! Goal seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Goal data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// GOAL SEEDER
// ============================================================================

/// Seeder for goal
pub struct SeedGoalSeeder;

impl SeedGoalSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedGoalSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedGoalSeeder {
    fn name(&self) -> &'static str {
        "SeedGoalSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if performance.goals table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM performance.goals")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/goal_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM performance.goals")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

