//! TalentMatrixEntry seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TalentMatrixEntry data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TALENTMATRIXENTRY SEEDER
// ============================================================================

/// Seeder for talent_matrix_entry
pub struct SeedTalentMatrixEntrySeeder;

impl SeedTalentMatrixEntrySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTalentMatrixEntrySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTalentMatrixEntrySeeder {
    fn name(&self) -> &'static str {
        "SeedTalentMatrixEntrySeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if performance.talent_matrix_entries table has any data
        let count: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM performance.talent_matrix_entries")
                .fetch_one(pool)
                .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/talent_matrix_entry_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM performance.talent_matrix_entries")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
