//! Repository trait for Appraisal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Appraisal aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Appraisal, AppraisalStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AppraisalPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AppraisalPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AppraisalPaginatedResult {
    pub data: Vec<Appraisal>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AppraisalFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub cycle_id: Option<Uuid>,
    pub reviewer_id: Option<Uuid>,
    pub status: Option<AppraisalStatus>,
}

impl AppraisalFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.cycle_id.is_some() || self.reviewer_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for Appraisal aggregate
///
/// This trait defines the persistence contract for Appraisal entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AppraisalRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new appraisal entity
    async fn save(&self, entity: &Appraisal) -> Result<Appraisal>;

    /// Find appraisal by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Appraisal>>;

    /// Find all appraisal entities
    async fn find_all(&self) -> Result<Vec<Appraisal>>;

    /// Update appraisal by ID
    async fn update(&self, id: &str, entity: &Appraisal) -> Result<Option<Appraisal>>;

    /// Delete appraisal by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List appraisal with pagination
    async fn list(&self, params: AppraisalPaginationParams) -> Result<AppraisalPaginatedResult>;

    /// List appraisal with pagination and filters
    async fn list_with_filters(&self, params: AppraisalPaginationParams, filters: AppraisalFilter) -> Result<AppraisalPaginatedResult>;

    /// Count all appraisal entities
    async fn count(&self) -> Result<u64>;

    /// Count appraisal entities matching filters
    async fn count_with_filters(&self, filters: AppraisalFilter) -> Result<u64>;

    /// Check if appraisal exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete appraisal by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted appraisal by ID
    async fn restore(&self, id: &str) -> Result<Option<Appraisal>>;

    /// List soft-deleted appraisal entities
    async fn list_deleted(&self, params: AppraisalPaginationParams) -> Result<AppraisalPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save appraisal entities
    async fn bulk_save(&self, entities: &[Appraisal]) -> Result<Vec<Appraisal>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
