//! Repository trait for AppraisalCycle aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AppraisalCycle aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AppraisalCycle, CycleStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AppraisalCyclePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AppraisalCyclePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AppraisalCyclePaginatedResult {
    pub data: Vec<AppraisalCycle>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AppraisalCycleFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub cycle_type: Option<String>,
    pub status: Option<CycleStatus>,
}

impl AppraisalCycleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.cycle_type.is_some() || self.status.is_some()
    }
}

/// Repository trait for AppraisalCycle aggregate
///
/// This trait defines the persistence contract for AppraisalCycle entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AppraisalCycleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new appraisal_cycle entity
    async fn save(&self, entity: &AppraisalCycle) -> Result<AppraisalCycle>;

    /// Find appraisal_cycle by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AppraisalCycle>>;

    /// Find all appraisal_cycle entities
    async fn find_all(&self) -> Result<Vec<AppraisalCycle>>;

    /// Update appraisal_cycle by ID
    async fn update(&self, id: &str, entity: &AppraisalCycle) -> Result<Option<AppraisalCycle>>;

    /// Delete appraisal_cycle by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List appraisal_cycle with pagination
    async fn list(&self, params: AppraisalCyclePaginationParams) -> Result<AppraisalCyclePaginatedResult>;

    /// List appraisal_cycle with pagination and filters
    async fn list_with_filters(&self, params: AppraisalCyclePaginationParams, filters: AppraisalCycleFilter) -> Result<AppraisalCyclePaginatedResult>;

    /// Count all appraisal_cycle entities
    async fn count(&self) -> Result<u64>;

    /// Count appraisal_cycle entities matching filters
    async fn count_with_filters(&self, filters: AppraisalCycleFilter) -> Result<u64>;

    /// Check if appraisal_cycle exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete appraisal_cycle by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted appraisal_cycle by ID
    async fn restore(&self, id: &str) -> Result<Option<AppraisalCycle>>;

    /// List soft-deleted appraisal_cycle entities
    async fn list_deleted(&self, params: AppraisalCyclePaginationParams) -> Result<AppraisalCyclePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save appraisal_cycle entities
    async fn bulk_save(&self, entities: &[AppraisalCycle]) -> Result<Vec<AppraisalCycle>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
