//! Repository trait for Feedback aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Feedback aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{Feedback, FeedbackRelationship};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FeedbackPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl FeedbackPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct FeedbackPaginatedResult {
    pub data: Vec<Feedback>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FeedbackFilter {
    pub cycle_id: Option<Uuid>,
    pub from_employee_id: Option<Uuid>,
    pub to_employee_id: Option<Uuid>,
    pub content: Option<String>,
    pub is_anonymous: Option<bool>,
    pub relationship: Option<FeedbackRelationship>,
}

impl FeedbackFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.cycle_id.is_some()
            || self.from_employee_id.is_some()
            || self.to_employee_id.is_some()
            || self.content.is_some()
            || self.is_anonymous.is_some()
            || self.relationship.is_some()
    }
}

/// Repository trait for Feedback aggregate
///
/// This trait defines the persistence contract for Feedback entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait FeedbackRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new feedback entity
    async fn save(&self, entity: &Feedback) -> Result<Feedback>;

    /// Find feedback by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Feedback>>;

    /// Find all feedback entities
    async fn find_all(&self) -> Result<Vec<Feedback>>;

    /// Update feedback by ID
    async fn update(&self, id: &str, entity: &Feedback) -> Result<Option<Feedback>>;

    /// Delete feedback by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List feedback with pagination
    async fn list(&self, params: FeedbackPaginationParams) -> Result<FeedbackPaginatedResult>;

    /// List feedback with pagination and filters
    async fn list_with_filters(
        &self,
        params: FeedbackPaginationParams,
        filters: FeedbackFilter,
    ) -> Result<FeedbackPaginatedResult>;

    /// Count all feedback entities
    async fn count(&self) -> Result<u64>;

    /// Count feedback entities matching filters
    async fn count_with_filters(&self, filters: FeedbackFilter) -> Result<u64>;

    /// Check if feedback exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete feedback by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted feedback by ID
    async fn restore(&self, id: &str) -> Result<Option<Feedback>>;

    /// List soft-deleted feedback entities
    async fn list_deleted(
        &self,
        params: FeedbackPaginationParams,
    ) -> Result<FeedbackPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save feedback entities
    async fn bulk_save(&self, entities: &[Feedback]) -> Result<Vec<Feedback>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
