//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod appraisal_repository;
pub mod appraisal_cycle_repository;
pub mod feedback_repository;
pub mod goal_repository;
pub mod reward_repository;
pub mod talent_matrix_entry_repository;

// Re-exports
pub use appraisal_repository::{
    AppraisalRepository,
    AppraisalPaginationParams,
    AppraisalPaginatedResult,
    AppraisalFilter,
};
pub use appraisal_cycle_repository::{
    AppraisalCycleRepository,
    AppraisalCyclePaginationParams,
    AppraisalCyclePaginatedResult,
    AppraisalCycleFilter,
};
pub use feedback_repository::{
    FeedbackRepository,
    FeedbackPaginationParams,
    FeedbackPaginatedResult,
    FeedbackFilter,
};
pub use goal_repository::{
    GoalRepository,
    GoalPaginationParams,
    GoalPaginatedResult,
    GoalFilter,
};
pub use reward_repository::{
    RewardRepository,
    RewardPaginationParams,
    RewardPaginatedResult,
    RewardFilter,
};
pub use talent_matrix_entry_repository::{
    TalentMatrixEntryRepository,
    TalentMatrixEntryPaginationParams,
    TalentMatrixEntryPaginatedResult,
    TalentMatrixEntryFilter,
};
