//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod appraisal_cycle_repository;
pub mod appraisal_repository;
pub mod feedback_repository;
pub mod goal_repository;
pub mod reward_repository;
pub mod talent_matrix_entry_repository;

// Re-exports
pub use appraisal_cycle_repository::{
    AppraisalCycleFilter, AppraisalCyclePaginatedResult, AppraisalCyclePaginationParams,
    AppraisalCycleRepository,
};
pub use appraisal_repository::{
    AppraisalFilter, AppraisalPaginatedResult, AppraisalPaginationParams, AppraisalRepository,
};
pub use feedback_repository::{
    FeedbackFilter, FeedbackPaginatedResult, FeedbackPaginationParams, FeedbackRepository,
};
pub use goal_repository::{GoalFilter, GoalPaginatedResult, GoalPaginationParams, GoalRepository};
pub use reward_repository::{
    RewardFilter, RewardPaginatedResult, RewardPaginationParams, RewardRepository,
};
pub use talent_matrix_entry_repository::{
    TalentMatrixEntryFilter, TalentMatrixEntryPaginatedResult, TalentMatrixEntryPaginationParams,
    TalentMatrixEntryRepository,
};
