//! Repository trait for Reward aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Reward aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Reward, RewardType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RewardPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RewardPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RewardPaginatedResult {
    pub data: Vec<Reward>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RewardFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub cycle_id: Option<Uuid>,
    pub reward_type: Option<RewardType>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub awarded_by: Option<Uuid>,
    pub payroll_component_id: Option<Uuid>,
}

impl RewardFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.cycle_id.is_some() || self.reward_type.is_some() || self.title.is_some() || self.description.is_some() || self.awarded_by.is_some() || self.payroll_component_id.is_some()
    }
}

/// Repository trait for Reward aggregate
///
/// This trait defines the persistence contract for Reward entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RewardRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new reward entity
    async fn save(&self, entity: &Reward) -> Result<Reward>;

    /// Find reward by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Reward>>;

    /// Find all reward entities
    async fn find_all(&self) -> Result<Vec<Reward>>;

    /// Update reward by ID
    async fn update(&self, id: &str, entity: &Reward) -> Result<Option<Reward>>;

    /// Delete reward by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List reward with pagination
    async fn list(&self, params: RewardPaginationParams) -> Result<RewardPaginatedResult>;

    /// List reward with pagination and filters
    async fn list_with_filters(&self, params: RewardPaginationParams, filters: RewardFilter) -> Result<RewardPaginatedResult>;

    /// Count all reward entities
    async fn count(&self) -> Result<u64>;

    /// Count reward entities matching filters
    async fn count_with_filters(&self, filters: RewardFilter) -> Result<u64>;

    /// Check if reward exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete reward by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted reward by ID
    async fn restore(&self, id: &str) -> Result<Option<Reward>>;

    /// List soft-deleted reward entities
    async fn list_deleted(&self, params: RewardPaginationParams) -> Result<RewardPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save reward entities
    async fn bulk_save(&self, entities: &[Reward]) -> Result<Vec<Reward>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
