//! Repository trait for TalentMatrixEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TalentMatrixEntry aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::TalentMatrixEntry;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TalentMatrixEntryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TalentMatrixEntryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TalentMatrixEntryPaginatedResult {
    pub data: Vec<TalentMatrixEntry>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TalentMatrixEntryFilter {
    pub employee_id: Option<Uuid>,
    pub cycle_id: Option<Uuid>,
    pub box_label: Option<String>,
}

impl TalentMatrixEntryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.cycle_id.is_some() || self.box_label.is_some()
    }
}

/// Repository trait for TalentMatrixEntry aggregate
///
/// This trait defines the persistence contract for TalentMatrixEntry entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TalentMatrixEntryRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new talent_matrix_entry entity
    async fn save(&self, entity: &TalentMatrixEntry) -> Result<TalentMatrixEntry>;

    /// Find talent_matrix_entry by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TalentMatrixEntry>>;

    /// Find all talent_matrix_entry entities
    async fn find_all(&self) -> Result<Vec<TalentMatrixEntry>>;

    /// Update talent_matrix_entry by ID
    async fn update(
        &self,
        id: &str,
        entity: &TalentMatrixEntry,
    ) -> Result<Option<TalentMatrixEntry>>;

    /// Delete talent_matrix_entry by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List talent_matrix_entry with pagination
    async fn list(
        &self,
        params: TalentMatrixEntryPaginationParams,
    ) -> Result<TalentMatrixEntryPaginatedResult>;

    /// List talent_matrix_entry with pagination and filters
    async fn list_with_filters(
        &self,
        params: TalentMatrixEntryPaginationParams,
        filters: TalentMatrixEntryFilter,
    ) -> Result<TalentMatrixEntryPaginatedResult>;

    /// Count all talent_matrix_entry entities
    async fn count(&self) -> Result<u64>;

    /// Count talent_matrix_entry entities matching filters
    async fn count_with_filters(&self, filters: TalentMatrixEntryFilter) -> Result<u64>;

    /// Check if talent_matrix_entry exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete talent_matrix_entry by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted talent_matrix_entry by ID
    async fn restore(&self, id: &str) -> Result<Option<TalentMatrixEntry>>;

    /// List soft-deleted talent_matrix_entry entities
    async fn list_deleted(
        &self,
        params: TalentMatrixEntryPaginationParams,
    ) -> Result<TalentMatrixEntryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save talent_matrix_entry entities
    async fn bulk_save(&self, entities: &[TalentMatrixEntry]) -> Result<Vec<TalentMatrixEntry>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
