//! Repository for Appraisal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Appraisal, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Appraisal;

/// Table name for Appraisal entities
pub const TABLE_NAME: &str = "performance.appraisals";

/// Repository for Appraisal entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AppraisalRepository(
    backbone_orm::GenericCrudRepository<Appraisal, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AppraisalRepository {
    type Target = backbone_orm::GenericCrudRepository<Appraisal, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AppraisalRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AppraisalRepository, Appraisal, soft_delete);
