//! Repository for AppraisalCycle entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AppraisalCycle, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AppraisalCycle;

/// Table name for AppraisalCycle entities
pub const TABLE_NAME: &str = "performance.appraisal_cycles";

/// Repository for AppraisalCycle entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AppraisalCycleRepository(
    backbone_orm::GenericCrudRepository<AppraisalCycle, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AppraisalCycleRepository {
    type Target = backbone_orm::GenericCrudRepository<AppraisalCycle, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AppraisalCycleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AppraisalCycleRepository, AppraisalCycle, soft_delete);
