//! Repository for Feedback entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Feedback, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Feedback;

/// Table name for Feedback entities
pub const TABLE_NAME: &str = "performance.performance_feedback";

/// Repository for Feedback entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct FeedbackRepository(
    backbone_orm::GenericCrudRepository<Feedback, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for FeedbackRepository {
    type Target = backbone_orm::GenericCrudRepository<Feedback, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl FeedbackRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(FeedbackRepository, Feedback, soft_delete);
