//! Repository for Goal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Goal, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Goal;

/// Table name for Goal entities
pub const TABLE_NAME: &str = "performance.goals";

/// Repository for Goal entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct GoalRepository(backbone_orm::GenericCrudRepository<Goal, backbone_orm::SoftDelete>);

impl std::ops::Deref for GoalRepository {
    type Target = backbone_orm::GenericCrudRepository<Goal, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl GoalRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(GoalRepository, Goal, soft_delete);
