//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod appraisal_cycle_repository;
mod appraisal_repository;
mod feedback_repository;
mod goal_repository;
mod reward_repository;
mod talent_matrix_entry_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use appraisal_cycle_repository::AppraisalCycleRepository;
pub use appraisal_repository::AppraisalRepository;
pub use feedback_repository::FeedbackRepository;
pub use goal_repository::GoalRepository;
pub use reward_repository::RewardRepository;
pub use talent_matrix_entry_repository::TalentMatrixEntryRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, FilterCondition, FilterParams, PaginatedResult, PaginationInfo,
    PaginationParams, PostgresRepository, SortDirection, SortParams,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
