//! Repository for TalentMatrixEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TalentMatrixEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TalentMatrixEntry;

/// Table name for TalentMatrixEntry entities
pub const TABLE_NAME: &str = "performance.talent_matrix_entries";

/// Repository for TalentMatrixEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TalentMatrixEntryRepository(
    backbone_orm::GenericCrudRepository<TalentMatrixEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TalentMatrixEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<TalentMatrixEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TalentMatrixEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TalentMatrixEntryRepository, TalentMatrixEntry, soft_delete);
