//! Validator for Appraisal entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Appraisal>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::Appraisal;

/// Validator type alias for Appraisal entities.
pub type AppraisalValidator = EntityValidator<Appraisal>;

/// Build a validator for Appraisal with all schema-defined field rules.
pub fn appraisal_validator() -> AppraisalValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
