//! Validator for AppraisalCycle entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AppraisalCycle>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::AppraisalCycle;

/// Validator type alias for AppraisalCycle entities.
pub type AppraisalCycleValidator = EntityValidator<AppraisalCycle>;

/// Build a validator for AppraisalCycle with all schema-defined field rules.
pub fn appraisal_cycle_validator() -> AppraisalCycleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &AppraisalCycle| &e.name))
        .rule(OptionalNotBlank::new("cycle_type", |e: &AppraisalCycle| e.cycle_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
