//! Validator for Goal entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Goal>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Goal;

/// Validator type alias for Goal entities.
pub type GoalValidator = EntityValidator<Goal>;

/// Build a validator for Goal with all schema-defined field rules.
pub fn goal_validator() -> GoalValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Goal| &e.title))
        .rule(OptionalNotBlank::new("description", |e: &Goal| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
