//! Validator for Reward entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Reward>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Reward;

/// Validator type alias for Reward entities.
pub type RewardValidator = EntityValidator<Reward>;

/// Build a validator for Reward with all schema-defined field rules.
pub fn reward_validator() -> RewardValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Reward| &e.title))
        .rule(OptionalNotBlank::new("description", |e: &Reward| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
