//! Auth configuration for AppraisalCycle handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AppraisalCycle>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AppraisalCycleService;
use crate::domain::entity::AppraisalCycle;

/// Permission string constants for AppraisalCycle operations.
pub mod permissions {
    pub const LIST:        &str = "appraisal_cycle:list";
    pub const READ:        &str = "appraisal_cycle:read";
    pub const CREATE:      &str = "appraisal_cycle:create";
    pub const UPDATE:      &str = "appraisal_cycle:update";
    pub const DELETE:      &str = "appraisal_cycle:delete";
    pub const RESTORE:     &str = "appraisal_cycle:restore";
    pub const TRASH:       &str = "appraisal_cycle:trash";
    pub const EMPTY_TRASH: &str = "appraisal_cycle:empty_trash";
    pub const BULK_CREATE: &str = "appraisal_cycle:bulk_create";
    pub const UPSERT:      &str = "appraisal_cycle:upsert";
}

/// Resource policy for AppraisalCycle — maps CRUD actions to permission strings.
pub struct AppraisalCyclePolicy;

#[async_trait]
impl ResourcePolicy<AppraisalCycle> for AppraisalCyclePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AppraisalCycle,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AppraisalCycle handlers.
///
/// Wraps `AppraisalCycleService` and checks `AppraisalCyclePolicy` before delegating.
pub type AppraisalCycleGuard = PermissionGuard<AppraisalCycle>;

/// Service-integrated permission guard for AppraisalCycle (for use in generated handlers).
pub type AppraisalCycleServiceGuard = ServicePermissionGuard<AppraisalCycle, AppraisalCycleService, AppraisalCyclePolicy>;

// <<< CUSTOM
// END CUSTOM
