//! Auth configuration for Appraisal handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Appraisal>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AppraisalService;
use crate::domain::entity::Appraisal;

/// Permission string constants for Appraisal operations.
pub mod permissions {
    pub const LIST:        &str = "appraisal:list";
    pub const READ:        &str = "appraisal:read";
    pub const CREATE:      &str = "appraisal:create";
    pub const UPDATE:      &str = "appraisal:update";
    pub const DELETE:      &str = "appraisal:delete";
    pub const RESTORE:     &str = "appraisal:restore";
    pub const TRASH:       &str = "appraisal:trash";
    pub const EMPTY_TRASH: &str = "appraisal:empty_trash";
    pub const BULK_CREATE: &str = "appraisal:bulk_create";
    pub const UPSERT:      &str = "appraisal:upsert";
}

/// Resource policy for Appraisal — maps CRUD actions to permission strings.
pub struct AppraisalPolicy;

#[async_trait]
impl ResourcePolicy<Appraisal> for AppraisalPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Appraisal,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Appraisal handlers.
///
/// Wraps `AppraisalService` and checks `AppraisalPolicy` before delegating.
pub type AppraisalGuard = PermissionGuard<Appraisal>;

/// Service-integrated permission guard for Appraisal (for use in generated handlers).
pub type AppraisalServiceGuard = ServicePermissionGuard<Appraisal, AppraisalService, AppraisalPolicy>;

// <<< CUSTOM
// END CUSTOM
