//! Auth configuration for Feedback handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Feedback>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::FeedbackService;
use crate::domain::entity::Feedback;

/// Permission string constants for Feedback operations.
pub mod permissions {
    pub const LIST:        &str = "feedback:list";
    pub const READ:        &str = "feedback:read";
    pub const CREATE:      &str = "feedback:create";
    pub const UPDATE:      &str = "feedback:update";
    pub const DELETE:      &str = "feedback:delete";
    pub const RESTORE:     &str = "feedback:restore";
    pub const TRASH:       &str = "feedback:trash";
    pub const EMPTY_TRASH: &str = "feedback:empty_trash";
    pub const BULK_CREATE: &str = "feedback:bulk_create";
    pub const UPSERT:      &str = "feedback:upsert";
}

/// Resource policy for Feedback — maps CRUD actions to permission strings.
pub struct FeedbackPolicy;

#[async_trait]
impl ResourcePolicy<Feedback> for FeedbackPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Feedback,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Feedback handlers.
///
/// Wraps `FeedbackService` and checks `FeedbackPolicy` before delegating.
pub type FeedbackGuard = PermissionGuard<Feedback>;

/// Service-integrated permission guard for Feedback (for use in generated handlers).
pub type FeedbackServiceGuard = ServicePermissionGuard<Feedback, FeedbackService, FeedbackPolicy>;

// <<< CUSTOM
// END CUSTOM
