//! Auth configuration for Goal handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Goal>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::GoalService;
use crate::domain::entity::Goal;

/// Permission string constants for Goal operations.
pub mod permissions {
    pub const LIST:        &str = "goal:list";
    pub const READ:        &str = "goal:read";
    pub const CREATE:      &str = "goal:create";
    pub const UPDATE:      &str = "goal:update";
    pub const DELETE:      &str = "goal:delete";
    pub const RESTORE:     &str = "goal:restore";
    pub const TRASH:       &str = "goal:trash";
    pub const EMPTY_TRASH: &str = "goal:empty_trash";
    pub const BULK_CREATE: &str = "goal:bulk_create";
    pub const UPSERT:      &str = "goal:upsert";
}

/// Resource policy for Goal — maps CRUD actions to permission strings.
pub struct GoalPolicy;

#[async_trait]
impl ResourcePolicy<Goal> for GoalPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Goal,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Goal handlers.
///
/// Wraps `GoalService` and checks `GoalPolicy` before delegating.
pub type GoalGuard = PermissionGuard<Goal>;

/// Service-integrated permission guard for Goal (for use in generated handlers).
pub type GoalServiceGuard = ServicePermissionGuard<Goal, GoalService, GoalPolicy>;

// <<< CUSTOM
// END CUSTOM
