//! Auth configuration for Reward handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Reward>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::RewardService;
use crate::domain::entity::Reward;

/// Permission string constants for Reward operations.
pub mod permissions {
    pub const LIST:        &str = "reward:list";
    pub const READ:        &str = "reward:read";
    pub const CREATE:      &str = "reward:create";
    pub const UPDATE:      &str = "reward:update";
    pub const DELETE:      &str = "reward:delete";
    pub const RESTORE:     &str = "reward:restore";
    pub const TRASH:       &str = "reward:trash";
    pub const EMPTY_TRASH: &str = "reward:empty_trash";
    pub const BULK_CREATE: &str = "reward:bulk_create";
    pub const UPSERT:      &str = "reward:upsert";
}

/// Resource policy for Reward — maps CRUD actions to permission strings.
pub struct RewardPolicy;

#[async_trait]
impl ResourcePolicy<Reward> for RewardPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Reward,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Reward handlers.
///
/// Wraps `RewardService` and checks `RewardPolicy` before delegating.
pub type RewardGuard = PermissionGuard<Reward>;

/// Service-integrated permission guard for Reward (for use in generated handlers).
pub type RewardServiceGuard = ServicePermissionGuard<Reward, RewardService, RewardPolicy>;

// <<< CUSTOM
// END CUSTOM
