//! Auth configuration for TalentMatrixEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TalentMatrixEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TalentMatrixEntryService;
use crate::domain::entity::TalentMatrixEntry;

/// Permission string constants for TalentMatrixEntry operations.
pub mod permissions {
    pub const LIST:        &str = "talent_matrix_entry:list";
    pub const READ:        &str = "talent_matrix_entry:read";
    pub const CREATE:      &str = "talent_matrix_entry:create";
    pub const UPDATE:      &str = "talent_matrix_entry:update";
    pub const DELETE:      &str = "talent_matrix_entry:delete";
    pub const RESTORE:     &str = "talent_matrix_entry:restore";
    pub const TRASH:       &str = "talent_matrix_entry:trash";
    pub const EMPTY_TRASH: &str = "talent_matrix_entry:empty_trash";
    pub const BULK_CREATE: &str = "talent_matrix_entry:bulk_create";
    pub const UPSERT:      &str = "talent_matrix_entry:upsert";
}

/// Resource policy for TalentMatrixEntry — maps CRUD actions to permission strings.
pub struct TalentMatrixEntryPolicy;

#[async_trait]
impl ResourcePolicy<TalentMatrixEntry> for TalentMatrixEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TalentMatrixEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TalentMatrixEntry handlers.
///
/// Wraps `TalentMatrixEntryService` and checks `TalentMatrixEntryPolicy` before delegating.
pub type TalentMatrixEntryGuard = PermissionGuard<TalentMatrixEntry>;

/// Service-integrated permission guard for TalentMatrixEntry (for use in generated handlers).
pub type TalentMatrixEntryServiceGuard = ServicePermissionGuard<TalentMatrixEntry, TalentMatrixEntryService, TalentMatrixEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
