//! AppraisalCycle API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AppraisalCycle CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// APPRAISALCYCLE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AppraisalCycle
pub struct AppraisalCycleTestData;

impl TestDataGenerator for AppraisalCycleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "cycle_type": null,
            "period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "cycle_type": null,
            "period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// APPRAISALCYCLE API TEST
// ============================================================================

/// AppraisalCycle API test suite
pub struct AppraisalCycleApiTest {
    inner: GenericCrudTest<AppraisalCycleTestData>,
}

impl AppraisalCycleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/appraisal_cycles", "AppraisalCycle");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AppraisalCycleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AppraisalCycleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_appraisal_cycle_crud() {
        let mut test = AppraisalCycleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AppraisalCycle specific tests here
// <<< CUSTOM TESTS END >>>
