//! Appraisal API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Appraisal CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// APPRAISAL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Appraisal
pub struct AppraisalTestData;

impl TestDataGenerator for AppraisalTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": Uuid::new_v4().to_string(),
            "reviewer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "overall_rating": null,
            "submitted_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": Uuid::new_v4().to_string(),
            "reviewer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "overall_rating": null,
            "submitted_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(
            api,
            "/api/v1/appraisal_cycles",
            &super::appraisal_cycle_api_test::AppraisalCycleTestData,
        )
        .await
        {
            deps.push(("cycle_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// APPRAISAL API TEST
// ============================================================================

/// Appraisal API test suite
pub struct AppraisalApiTest {
    inner: GenericCrudTest<AppraisalTestData>,
}

impl AppraisalApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/appraisals", "Appraisal");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AppraisalTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AppraisalApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_appraisal_crud() {
        let mut test = AppraisalApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Appraisal specific tests here
// <<< CUSTOM TESTS END >>>
