//! Feedback API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Feedback CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// FEEDBACK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Feedback
pub struct FeedbackTestData;

impl TestDataGenerator for FeedbackTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "cycle_id": null,
            "from_employee_id": Uuid::new_v4().to_string(),
            "to_employee_id": Uuid::new_v4().to_string(),
            "content": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_anonymous": false,
            "relationship": "peer",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "cycle_id": null,
            "from_employee_id": Uuid::new_v4().to_string(),
            "to_employee_id": Uuid::new_v4().to_string(),
            "content": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_anonymous": false,
            "relationship": "peer",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// FEEDBACK API TEST
// ============================================================================

/// Feedback API test suite
pub struct FeedbackApiTest {
    inner: GenericCrudTest<FeedbackTestData>,
}

impl FeedbackApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/performance_feedback", "Feedback");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, FeedbackTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for FeedbackApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_feedback_crud() {
        let mut test = FeedbackApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Feedback specific tests here
// <<< CUSTOM TESTS END >>>
