//! Goal API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Goal CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// GOAL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Goal
pub struct GoalTestData;

impl TestDataGenerator for GoalTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "weight": null,
            "progress": null,
            "parent_goal_id": null,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "weight": null,
            "progress": null,
            "parent_goal_id": null,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// GOAL API TEST
// ============================================================================

/// Goal API test suite
pub struct GoalApiTest {
    inner: GenericCrudTest<GoalTestData>,
}

impl GoalApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/goals", "Goal");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, GoalTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for GoalApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_goal_crud() {
        let mut test = GoalApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Goal specific tests here
// <<< CUSTOM TESTS END >>>
