//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod appraisal_api_test;
pub mod appraisal_cycle_api_test;
pub mod feedback_api_test;
pub mod goal_api_test;
pub mod reward_api_test;
pub mod talent_matrix_entry_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use appraisal_api_test::*;
pub use appraisal_cycle_api_test::*;
pub use feedback_api_test::*;
pub use goal_api_test::*;
pub use reward_api_test::*;
pub use talent_matrix_entry_api_test::*;
