//! Reward API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Reward CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// REWARD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Reward
pub struct RewardTestData;

impl TestDataGenerator for RewardTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": null,
            "reward_type": "recognition",
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "amount": null,
            "awarded_by": null,
            "awarded_at": now,
            "payroll_component_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "cycle_id": null,
            "reward_type": "recognition",
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "amount": null,
            "awarded_by": null,
            "awarded_at": now,
            "payroll_component_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// REWARD API TEST
// ============================================================================

/// Reward API test suite
pub struct RewardApiTest {
    inner: GenericCrudTest<RewardTestData>,
}

impl RewardApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/rewards", "Reward");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RewardTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RewardApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_reward_crud() {
        let mut test = RewardApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Reward specific tests here
// <<< CUSTOM TESTS END >>>
