//! Performance Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AppraisalService;
use crate::application::service::AppraisalCycleService;
use crate::application::service::FeedbackService;
use crate::application::service::GoalService;
use crate::application::service::RewardService;
use crate::application::service::TalentMatrixEntryService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Appraisal service
    pub appraisal_service: Arc<AppraisalService>,
    /// AppraisalCycle service
    pub appraisal_cycle_service: Arc<AppraisalCycleService>,
    /// Feedback service
    pub feedback_service: Arc<FeedbackService>,
    /// Goal service
    pub goal_service: Arc<GoalService>,
    /// Reward service
    pub reward_service: Arc<RewardService>,
    /// TalentMatrixEntry service
    pub talent_matrix_entry_service: Arc<TalentMatrixEntryService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        appraisal_service: Arc<AppraisalService>,
        appraisal_cycle_service: Arc<AppraisalCycleService>,
        feedback_service: Arc<FeedbackService>,
        goal_service: Arc<GoalService>,
        reward_service: Arc<RewardService>,
        talent_matrix_entry_service: Arc<TalentMatrixEntryService>
    ) -> Self {
        Self {
            appraisal_service,
            appraisal_cycle_service,
            feedback_service,
            goal_service,
            reward_service,
            talent_matrix_entry_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PerformanceModule) -> Self {
        Self {
            appraisal_service: module.appraisal_service.clone(),
            appraisal_cycle_service: module.appraisal_cycle_service.clone(),
            feedback_service: module.feedback_service.clone(),
            goal_service: module.goal_service.clone(),
            reward_service: module.reward_service.clone(),
            talent_matrix_entry_service: module.talent_matrix_entry_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    appraisal_service: Option<Arc<AppraisalService>>,
    appraisal_cycle_service: Option<Arc<AppraisalCycleService>>,
    feedback_service: Option<Arc<FeedbackService>>,
    goal_service: Option<Arc<GoalService>>,
    reward_service: Option<Arc<RewardService>>,
    talent_matrix_entry_service: Option<Arc<TalentMatrixEntryService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Appraisal service.
    pub fn with_appraisal_service(mut self, service: Arc<AppraisalService>) -> Self {
        self.appraisal_service = Some(service);
        self
    }

    /// Set the AppraisalCycle service.
    pub fn with_appraisal_cycle_service(mut self, service: Arc<AppraisalCycleService>) -> Self {
        self.appraisal_cycle_service = Some(service);
        self
    }

    /// Set the Feedback service.
    pub fn with_feedback_service(mut self, service: Arc<FeedbackService>) -> Self {
        self.feedback_service = Some(service);
        self
    }

    /// Set the Goal service.
    pub fn with_goal_service(mut self, service: Arc<GoalService>) -> Self {
        self.goal_service = Some(service);
        self
    }

    /// Set the Reward service.
    pub fn with_reward_service(mut self, service: Arc<RewardService>) -> Self {
        self.reward_service = Some(service);
        self
    }

    /// Set the TalentMatrixEntry service.
    pub fn with_talent_matrix_entry_service(mut self, service: Arc<TalentMatrixEntryService>) -> Self {
        self.talent_matrix_entry_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            appraisal_service: self.appraisal_service.expect("appraisal_service is required"),
            appraisal_cycle_service: self.appraisal_cycle_service.expect("appraisal_cycle_service is required"),
            feedback_service: self.feedback_service.expect("feedback_service is required"),
            goal_service: self.goal_service.expect("goal_service is required"),
            reward_service: self.reward_service.expect("reward_service is required"),
            talent_matrix_entry_service: self.talent_matrix_entry_service.expect("talent_matrix_entry_service is required"),
        }
    }
}
