//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    appraisal_handler::create_appraisal_routes,
    appraisal_cycle_handler::create_appraisal_cycle_routes,
    feedback_handler::create_feedback_routes,
    goal_handler::create_goal_routes,
    reward_handler::create_reward_routes,
    talent_matrix_entry_handler::create_talent_matrix_entry_routes,
};

use crate::application::service::{
    AppraisalService,
    AppraisalCycleService,
    FeedbackService,
    GoalService,
    RewardService,
    TalentMatrixEntryService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub appraisal: Arc<AppraisalService>,
    pub appraisal_cycle: Arc<AppraisalCycleService>,
    pub feedback: Arc<FeedbackService>,
    pub goal: Arc<GoalService>,
    pub reward: Arc<RewardService>,
    pub talent_matrix_entry: Arc<TalentMatrixEntryService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Appraisal routes (12 Backbone endpoints)
        .merge(create_appraisal_routes(services.appraisal))
        // AppraisalCycle routes (12 Backbone endpoints)
        .merge(create_appraisal_cycle_routes(services.appraisal_cycle))
        // Feedback routes (12 Backbone endpoints)
        .merge(create_feedback_routes(services.feedback))
        // Goal routes (12 Backbone endpoints)
        .merge(create_goal_routes(services.goal))
        // Reward routes (12 Backbone endpoints)
        .merge(create_reward_routes(services.reward))
        // TalentMatrixEntry routes (12 Backbone endpoints)
        .merge(create_talent_matrix_entry_routes(services.talent_matrix_entry))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn appraisal_routes(service: Arc<AppraisalService>) -> Router {
        create_appraisal_routes(service)
    }

    pub fn appraisal_cycle_routes(service: Arc<AppraisalCycleService>) -> Router {
        create_appraisal_cycle_routes(service)
    }

    pub fn feedback_routes(service: Arc<FeedbackService>) -> Router {
        create_feedback_routes(service)
    }

    pub fn goal_routes(service: Arc<GoalService>) -> Router {
        create_goal_routes(service)
    }

    pub fn reward_routes(service: Arc<RewardService>) -> Router {
        create_reward_routes(service)
    }

    pub fn talent_matrix_entry_routes(service: Arc<TalentMatrixEntryService>) -> Router {
        create_talent_matrix_entry_routes(service)
    }

}
