//! Public events for Performance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::types::*;

// ============================================================================
// APPRAISAL EVENTS
// ============================================================================

/// Event published when a Appraisal is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCreatedEvent {
    pub id: AppraisalId,
    pub data: AppraisalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Appraisal is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalUpdatedEvent {
    pub id: AppraisalId,
    pub data: AppraisalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Appraisal is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalDeletedEvent {
    pub id: AppraisalId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// APPRAISALCYCLE EVENTS
// ============================================================================

/// Event published when a AppraisalCycle is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleCreatedEvent {
    pub id: AppraisalCycleId,
    pub data: AppraisalCycleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AppraisalCycle is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleUpdatedEvent {
    pub id: AppraisalCycleId,
    pub data: AppraisalCycleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AppraisalCycle is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleDeletedEvent {
    pub id: AppraisalCycleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// FEEDBACK EVENTS
// ============================================================================

/// Event published when a Feedback is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackCreatedEvent {
    pub id: FeedbackId,
    pub data: FeedbackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Feedback is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackUpdatedEvent {
    pub id: FeedbackId,
    pub data: FeedbackDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Feedback is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackDeletedEvent {
    pub id: FeedbackId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// GOAL EVENTS
// ============================================================================

/// Event published when a Goal is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalCreatedEvent {
    pub id: GoalId,
    pub data: GoalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Goal is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalUpdatedEvent {
    pub id: GoalId,
    pub data: GoalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Goal is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalDeletedEvent {
    pub id: GoalId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// REWARD EVENTS
// ============================================================================

/// Event published when a Reward is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardCreatedEvent {
    pub id: RewardId,
    pub data: RewardDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Reward is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardUpdatedEvent {
    pub id: RewardId,
    pub data: RewardDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Reward is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardDeletedEvent {
    pub id: RewardId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TALENTMATRIXENTRY EVENTS
// ============================================================================

/// Event published when a TalentMatrixEntry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntryCreatedEvent {
    pub id: TalentMatrixEntryId,
    pub data: TalentMatrixEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TalentMatrixEntry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntryUpdatedEvent {
    pub id: TalentMatrixEntryId,
    pub data: TalentMatrixEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TalentMatrixEntry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntryDeletedEvent {
    pub id: TalentMatrixEntryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Performance module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PerformanceEvent {
    AppraisalCreated(AppraisalCreatedEvent),
    AppraisalUpdated(AppraisalUpdatedEvent),
    AppraisalDeleted(AppraisalDeletedEvent),
    AppraisalCycleCreated(AppraisalCycleCreatedEvent),
    AppraisalCycleUpdated(AppraisalCycleUpdatedEvent),
    AppraisalCycleDeleted(AppraisalCycleDeletedEvent),
    FeedbackCreated(FeedbackCreatedEvent),
    FeedbackUpdated(FeedbackUpdatedEvent),
    FeedbackDeleted(FeedbackDeletedEvent),
    GoalCreated(GoalCreatedEvent),
    GoalUpdated(GoalUpdatedEvent),
    GoalDeleted(GoalDeletedEvent),
    RewardCreated(RewardCreatedEvent),
    RewardUpdated(RewardUpdatedEvent),
    RewardDeleted(RewardDeletedEvent),
    TalentMatrixEntryCreated(TalentMatrixEntryCreatedEvent),
    TalentMatrixEntryUpdated(TalentMatrixEntryUpdatedEvent),
    TalentMatrixEntryDeleted(TalentMatrixEntryDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PerformanceEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PerformanceEventMetadata {
    fn default() -> Self {
        Self {
            module: "performance",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
