//! Performance Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Performance exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use performance::exports::{AppraisalDto};
//! ```

mod events;
mod services;
mod types;

// Re-export all public types
pub use events::*;
pub use services::*;
pub use types::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AppraisalDto` - Data transfer object for Appraisal
/// - `AppraisalSummary` - Summary view of Appraisal
/// - `AppraisalId` - Type-safe ID wrapper
/// - `AppraisalCycleDto` - Data transfer object for AppraisalCycle
/// - `AppraisalCycleSummary` - Summary view of AppraisalCycle
/// - `AppraisalCycleId` - Type-safe ID wrapper
/// - `FeedbackDto` - Data transfer object for Feedback
/// - `FeedbackSummary` - Summary view of Feedback
/// - `FeedbackId` - Type-safe ID wrapper
/// - `GoalDto` - Data transfer object for Goal
/// - `GoalSummary` - Summary view of Goal
/// - `GoalId` - Type-safe ID wrapper
/// - `RewardDto` - Data transfer object for Reward
/// - `RewardSummary` - Summary view of Reward
/// - `RewardId` - Type-safe ID wrapper
/// - `TalentMatrixEntryDto` - Data transfer object for TalentMatrixEntry
/// - `TalentMatrixEntrySummary` - Summary view of TalentMatrixEntry
/// - `TalentMatrixEntryId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `AppraisalCreatedEvent` - Published when Appraisal is created
/// - `AppraisalUpdatedEvent` - Published when Appraisal is updated
/// - `AppraisalDeletedEvent` - Published when Appraisal is deleted
/// - `AppraisalCycleCreatedEvent` - Published when AppraisalCycle is created
/// - `AppraisalCycleUpdatedEvent` - Published when AppraisalCycle is updated
/// - `AppraisalCycleDeletedEvent` - Published when AppraisalCycle is deleted
/// - `FeedbackCreatedEvent` - Published when Feedback is created
/// - `FeedbackUpdatedEvent` - Published when Feedback is updated
/// - `FeedbackDeletedEvent` - Published when Feedback is deleted
/// - `GoalCreatedEvent` - Published when Goal is created
/// - `GoalUpdatedEvent` - Published when Goal is updated
/// - `GoalDeletedEvent` - Published when Goal is deleted
/// - `RewardCreatedEvent` - Published when Reward is created
/// - `RewardUpdatedEvent` - Published when Reward is updated
/// - `RewardDeletedEvent` - Published when Reward is deleted
/// - `TalentMatrixEntryCreatedEvent` - Published when TalentMatrixEntry is created
/// - `TalentMatrixEntryUpdatedEvent` - Published when TalentMatrixEntry is updated
/// - `TalentMatrixEntryDeletedEvent` - Published when TalentMatrixEntry is deleted
pub struct ExportSummary;
