//! Public services for Performance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Performance module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PerformanceQueryService: Send + Sync {
    /// Get Appraisal by ID
    async fn get_appraisal(&self, id: AppraisalId) -> Result<Option<AppraisalDto>>;

    /// Get Appraisal summary by ID
    async fn get_appraisal_summary(&self, id: AppraisalId) -> Result<Option<AppraisalSummary>>;

    /// Check if Appraisal exists
    async fn appraisal_exists(&self, id: AppraisalId) -> Result<bool>;

    /// Get AppraisalCycle by ID
    async fn get_appraisal_cycle(&self, id: AppraisalCycleId) -> Result<Option<AppraisalCycleDto>>;

    /// Get AppraisalCycle summary by ID
    async fn get_appraisal_cycle_summary(&self, id: AppraisalCycleId) -> Result<Option<AppraisalCycleSummary>>;

    /// Check if AppraisalCycle exists
    async fn appraisal_cycle_exists(&self, id: AppraisalCycleId) -> Result<bool>;

    /// Get Feedback by ID
    async fn get_feedback(&self, id: FeedbackId) -> Result<Option<FeedbackDto>>;

    /// Get Feedback summary by ID
    async fn get_feedback_summary(&self, id: FeedbackId) -> Result<Option<FeedbackSummary>>;

    /// Check if Feedback exists
    async fn feedback_exists(&self, id: FeedbackId) -> Result<bool>;

    /// Get Goal by ID
    async fn get_goal(&self, id: GoalId) -> Result<Option<GoalDto>>;

    /// Get Goal summary by ID
    async fn get_goal_summary(&self, id: GoalId) -> Result<Option<GoalSummary>>;

    /// Check if Goal exists
    async fn goal_exists(&self, id: GoalId) -> Result<bool>;

    /// Get Reward by ID
    async fn get_reward(&self, id: RewardId) -> Result<Option<RewardDto>>;

    /// Get Reward summary by ID
    async fn get_reward_summary(&self, id: RewardId) -> Result<Option<RewardSummary>>;

    /// Check if Reward exists
    async fn reward_exists(&self, id: RewardId) -> Result<bool>;

    /// Get TalentMatrixEntry by ID
    async fn get_talent_matrix_entry(&self, id: TalentMatrixEntryId) -> Result<Option<TalentMatrixEntryDto>>;

    /// Get TalentMatrixEntry summary by ID
    async fn get_talent_matrix_entry_summary(&self, id: TalentMatrixEntryId) -> Result<Option<TalentMatrixEntrySummary>>;

    /// Check if TalentMatrixEntry exists
    async fn talent_matrix_entry_exists(&self, id: TalentMatrixEntryId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
