//! Public types for Performance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use crate::domain::entity::*;
use chrono::{DateTime, NaiveDate, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============================================================================
// APPRAISAL TYPES
// ============================================================================

/// Type-safe ID for Appraisal
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AppraisalId(pub Uuid);

impl AppraisalId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AppraisalId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AppraisalId> for Uuid {
    fn from(id: AppraisalId) -> Self {
        id.0
    }
}

/// Data transfer object for Appraisal
///
/// This is the public representation of Appraisal for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalDto {
    pub id: AppraisalId,
    pub employee_id: Uuid,
    pub cycle_id: Uuid,
    pub reviewer_id: Uuid,
    pub status: AppraisalStatus,
    pub overall_rating: Option<Decimal>,
    pub submitted_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Appraisal for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalSummary {
    pub id: AppraisalId,
    pub status: AppraisalStatus,
}

/// Reference to Appraisal for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalRef {
    pub id: AppraisalId,
}

// ============================================================================
// APPRAISALCYCLE TYPES
// ============================================================================

/// Type-safe ID for AppraisalCycle
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AppraisalCycleId(pub Uuid);

impl AppraisalCycleId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AppraisalCycleId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AppraisalCycleId> for Uuid {
    fn from(id: AppraisalCycleId) -> Self {
        id.0
    }
}

/// Data transfer object for AppraisalCycle
///
/// This is the public representation of AppraisalCycle for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleDto {
    pub id: AppraisalCycleId,
    pub name: String,
    pub cycle_type: Option<String>,
    pub period_start: NaiveDate,
    pub period_end: NaiveDate,
    pub status: CycleStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of AppraisalCycle for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleSummary {
    pub id: AppraisalCycleId,
    pub name: String,
    pub status: CycleStatus,
}

/// Reference to AppraisalCycle for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppraisalCycleRef {
    pub id: AppraisalCycleId,
}

// ============================================================================
// FEEDBACK TYPES
// ============================================================================

/// Type-safe ID for Feedback
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct FeedbackId(pub Uuid);

impl FeedbackId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for FeedbackId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<FeedbackId> for Uuid {
    fn from(id: FeedbackId) -> Self {
        id.0
    }
}

/// Data transfer object for Feedback
///
/// This is the public representation of Feedback for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackDto {
    pub id: FeedbackId,
    pub cycle_id: Option<Uuid>,
    pub from_employee_id: Uuid,
    pub to_employee_id: Uuid,
    pub content: String,
    pub is_anonymous: bool,
    pub relationship: FeedbackRelationship,
    pub metadata: serde_json::Value,
}

/// Summary view of Feedback for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackSummary {
    pub id: FeedbackId,
}

/// Reference to Feedback for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackRef {
    pub id: FeedbackId,
}

// ============================================================================
// GOAL TYPES
// ============================================================================

/// Type-safe ID for Goal
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GoalId(pub Uuid);

impl GoalId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for GoalId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<GoalId> for Uuid {
    fn from(id: GoalId) -> Self {
        id.0
    }
}

/// Data transfer object for Goal
///
/// This is the public representation of Goal for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalDto {
    pub id: GoalId,
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub title: String,
    pub description: Option<String>,
    pub weight: Option<Decimal>,
    pub progress: Option<Decimal>,
    pub parent_goal_id: Option<Uuid>,
    pub status: GoalStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Goal for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalSummary {
    pub id: GoalId,
    pub title: String,
    pub status: GoalStatus,
}

/// Reference to Goal for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalRef {
    pub id: GoalId,
}

// ============================================================================
// REWARD TYPES
// ============================================================================

/// Type-safe ID for Reward
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RewardId(pub Uuid);

impl RewardId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RewardId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RewardId> for Uuid {
    fn from(id: RewardId) -> Self {
        id.0
    }
}

/// Data transfer object for Reward
///
/// This is the public representation of Reward for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardDto {
    pub id: RewardId,
    pub employee_id: Uuid,
    pub cycle_id: Option<Uuid>,
    pub reward_type: RewardType,
    pub title: String,
    pub description: Option<String>,
    pub amount: Option<Decimal>,
    pub awarded_by: Option<Uuid>,
    pub awarded_at: NaiveDate,
    pub payroll_component_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Reward for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardSummary {
    pub id: RewardId,
    pub title: String,
}

/// Reference to Reward for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RewardRef {
    pub id: RewardId,
}

// ============================================================================
// TALENTMATRIXENTRY TYPES
// ============================================================================

/// Type-safe ID for TalentMatrixEntry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TalentMatrixEntryId(pub Uuid);

impl TalentMatrixEntryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for TalentMatrixEntryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<TalentMatrixEntryId> for Uuid {
    fn from(id: TalentMatrixEntryId) -> Self {
        id.0
    }
}

/// Data transfer object for TalentMatrixEntry
///
/// This is the public representation of TalentMatrixEntry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntryDto {
    pub id: TalentMatrixEntryId,
    pub employee_id: Uuid,
    pub cycle_id: Uuid,
    pub performance_score: i32,
    pub potential_score: i32,
    pub box_label: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of TalentMatrixEntry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntrySummary {
    pub id: TalentMatrixEntryId,
}

/// Reference to TalentMatrixEntry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalentMatrixEntryRef {
    pub id: TalentMatrixEntryId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
