//! Performance Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AppraisalService;
pub use application::service::AppraisalCycleService;
pub use application::service::FeedbackService;
pub use application::service::GoalService;
pub use application::service::RewardService;
pub use application::service::TalentMatrixEntryService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Performance module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let performance = PerformanceModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = performance.all_crud_routes();
/// ```
pub struct PerformanceModule {
    pub(crate) appraisal_service: Arc<AppraisalService>,
    pub(crate) appraisal_cycle_service: Arc<AppraisalCycleService>,
    pub(crate) feedback_service: Arc<FeedbackService>,
    pub(crate) goal_service: Arc<GoalService>,
    pub(crate) reward_service: Arc<RewardService>,
    pub(crate) talent_matrix_entry_service: Arc<TalentMatrixEntryService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl PerformanceModule {
    /// Create a new module builder
    pub fn builder() -> PerformanceModuleBuilder {
        PerformanceModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_appraisal_routes,
            create_appraisal_cycle_routes,
            create_feedback_routes,
            create_goal_routes,
            create_reward_routes,
            create_talent_matrix_entry_routes,
        };

        Router::new()
            .merge(create_appraisal_routes(self.appraisal_service.clone()))
            .merge(create_appraisal_cycle_routes(self.appraisal_cycle_service.clone()))
            .merge(create_feedback_routes(self.feedback_service.clone()))
            .merge(create_goal_routes(self.goal_service.clone()))
            .merge(create_reward_routes(self.reward_service.clone()))
            .merge(create_talent_matrix_entry_routes(self.talent_matrix_entry_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for PerformanceModule
pub struct PerformanceModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PerformanceModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PerformanceModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Appraisal service
        let appraisal_repository = Arc::new(AppraisalRepository::new(db_pool.clone()));
        let appraisal_service = Arc::new(AppraisalService::with_repository(appraisal_repository.clone()));

        // AppraisalCycle service
        let appraisal_cycle_repository = Arc::new(AppraisalCycleRepository::new(db_pool.clone()));
        let appraisal_cycle_service = Arc::new(AppraisalCycleService::with_repository(appraisal_cycle_repository.clone()));

        // Feedback service
        let feedback_repository = Arc::new(FeedbackRepository::new(db_pool.clone()));
        let feedback_service = Arc::new(FeedbackService::with_repository(feedback_repository.clone()));

        // Goal service
        let goal_repository = Arc::new(GoalRepository::new(db_pool.clone()));
        let goal_service = Arc::new(GoalService::with_repository(goal_repository.clone()));

        // Reward service
        let reward_repository = Arc::new(RewardRepository::new(db_pool.clone()));
        let reward_service = Arc::new(RewardService::with_repository(reward_repository.clone()));

        // TalentMatrixEntry service
        let talent_matrix_entry_repository = Arc::new(TalentMatrixEntryRepository::new(db_pool.clone()));
        let talent_matrix_entry_service = Arc::new(TalentMatrixEntryService::with_repository(talent_matrix_entry_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(PerformanceModule {
            appraisal_service,
            appraisal_cycle_service,
            feedback_service,
            goal_service,
            reward_service,
            talent_matrix_entry_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PerformanceModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
