//! Performance Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;
// <<< CUSTOM MODULES
// END CUSTOM

// The module's extension (hand-written; ADR-0031).
#[path = "lib.ext.rs"]
mod lib_ext;
pub use lib_ext::*;
/// This crate's module and builder under fixed names, for the extension's `impl` blocks.
#[allow(dead_code)]
pub(crate) type ThisModule = PerformanceModule;
#[allow(dead_code)]
pub(crate) type ThisModuleBuilder = PerformanceModuleBuilder;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AppraisalService;
pub use application::service::AppraisalCycleService;
pub use application::service::FeedbackService;
pub use application::service::GoalService;
pub use application::service::RewardService;
pub use application::service::TalentMatrixEntryService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Performance module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let performance = PerformanceModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = performance.all_crud_routes();
/// ```
pub struct PerformanceModule {
    pub(crate) appraisal_service: Arc<AppraisalService>,
    pub(crate) appraisal_cycle_service: Arc<AppraisalCycleService>,
    pub(crate) feedback_service: Arc<FeedbackService>,
    pub(crate) goal_service: Arc<GoalService>,
    pub(crate) reward_service: Arc<RewardService>,
    pub(crate) talent_matrix_entry_service: Arc<TalentMatrixEntryService>,
    /// The module's extension state (`lib.ext.rs`); its fields read through `Deref`.
    pub(crate) ext: ModuleExt,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl std::ops::Deref for PerformanceModule {
    type Target = ModuleExt;
    fn deref(&self) -> &Self::Target {
        &self.ext
    }
}

impl std::ops::DerefMut for PerformanceModule {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.ext
    }
}

/// What the extension's `build` hook receives from the generated build (ADR-0031).
#[allow(dead_code)]
pub(crate) struct ModuleParts<'a> {
    pub(crate) db_pool: &'a PgPool,
    pub(crate) appraisal_service: &'a Arc<AppraisalService>,
    pub(crate) appraisal_repository: &'a Arc<AppraisalRepository>,
    pub(crate) appraisal_cycle_service: &'a Arc<AppraisalCycleService>,
    pub(crate) appraisal_cycle_repository: &'a Arc<AppraisalCycleRepository>,
    pub(crate) feedback_service: &'a Arc<FeedbackService>,
    pub(crate) feedback_repository: &'a Arc<FeedbackRepository>,
    pub(crate) goal_service: &'a Arc<GoalService>,
    pub(crate) goal_repository: &'a Arc<GoalRepository>,
    pub(crate) reward_service: &'a Arc<RewardService>,
    pub(crate) reward_repository: &'a Arc<RewardRepository>,
    pub(crate) talent_matrix_entry_service: &'a Arc<TalentMatrixEntryService>,
    pub(crate) talent_matrix_entry_repository: &'a Arc<TalentMatrixEntryRepository>,
}

impl PerformanceModule {
    /// Create a new module builder
    pub fn builder() -> PerformanceModuleBuilder {
        PerformanceModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_appraisal_routes,
            create_appraisal_cycle_routes,
            create_feedback_routes,
            create_goal_routes,
            create_reward_routes,
            create_talent_matrix_entry_routes,
        };

        Router::new()
            .merge(create_appraisal_routes(self.appraisal_service.clone()))
            .merge(create_appraisal_cycle_routes(self.appraisal_cycle_service.clone()))
            .merge(create_feedback_routes(self.feedback_service.clone()))
            .merge(create_goal_routes(self.goal_service.clone()))
            .merge(create_reward_routes(self.reward_service.clone()))
            .merge(create_talent_matrix_entry_routes(self.talent_matrix_entry_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_appraisal_read_routes,
            create_appraisal_cycle_read_routes,
            create_feedback_read_routes,
            create_goal_read_routes,
            create_reward_read_routes,
            create_talent_matrix_entry_read_routes,
        };

        Router::new()
            .merge(create_appraisal_read_routes(self.appraisal_service.clone()))
            .merge(create_appraisal_cycle_read_routes(self.appraisal_cycle_service.clone()))
            .merge(create_feedback_read_routes(self.feedback_service.clone()))
            .merge(create_goal_read_routes(self.goal_service.clone()))
            .merge(create_reward_read_routes(self.reward_service.clone()))
            .merge(create_talent_matrix_entry_read_routes(self.talent_matrix_entry_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for PerformanceModule
pub struct PerformanceModuleBuilder {
    db_pool: Option<PgPool>,
    /// The builder's extension state (`lib.ext.rs`); its fields read through `Deref`.
    ext: ModuleBuilderExt,
    // <<< CUSTOM BUILDER FIELDS
    // END CUSTOM
}

impl std::ops::Deref for PerformanceModuleBuilder {
    type Target = ModuleBuilderExt;
    fn deref(&self) -> &Self::Target {
        &self.ext
    }
}

impl std::ops::DerefMut for PerformanceModuleBuilder {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.ext
    }
}

impl PerformanceModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            ext: Default::default(),
            // <<< CUSTOM BUILDER DEFAULTS
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PerformanceModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Appraisal service
        let appraisal_repository = Arc::new(AppraisalRepository::new(db_pool.clone()));
        let appraisal_service = Arc::new(AppraisalService::with_repository(appraisal_repository.clone()));

        // AppraisalCycle service
        let appraisal_cycle_repository = Arc::new(AppraisalCycleRepository::new(db_pool.clone()));
        let appraisal_cycle_service = Arc::new(AppraisalCycleService::with_repository(appraisal_cycle_repository.clone()));

        // Feedback service
        let feedback_repository = Arc::new(FeedbackRepository::new(db_pool.clone()));
        let feedback_service = Arc::new(FeedbackService::with_repository(feedback_repository.clone()));

        // Goal service
        let goal_repository = Arc::new(GoalRepository::new(db_pool.clone()));
        let goal_service = Arc::new(GoalService::with_repository(goal_repository.clone()));

        // Reward service
        let reward_repository = Arc::new(RewardRepository::new(db_pool.clone()));
        let reward_service = Arc::new(RewardService::with_repository(reward_repository.clone()));

        // TalentMatrixEntry service
        let talent_matrix_entry_repository = Arc::new(TalentMatrixEntryRepository::new(db_pool.clone()));
        let talent_matrix_entry_service = Arc::new(TalentMatrixEntryService::with_repository(talent_matrix_entry_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        // The extension builds its own state from what the generated build made.
        let ext = self.ext.build(&ModuleParts {
            db_pool: &db_pool,
            appraisal_service: &appraisal_service,
            appraisal_repository: &appraisal_repository,
            appraisal_cycle_service: &appraisal_cycle_service,
            appraisal_cycle_repository: &appraisal_cycle_repository,
            feedback_service: &feedback_service,
            feedback_repository: &feedback_repository,
            goal_service: &goal_service,
            goal_repository: &goal_repository,
            reward_service: &reward_service,
            reward_repository: &reward_repository,
            talent_matrix_entry_service: &talent_matrix_entry_service,
            talent_matrix_entry_repository: &talent_matrix_entry_repository,
        })?;

        Ok(PerformanceModule {
            appraisal_service,
            appraisal_cycle_service,
            feedback_service,
            goal_service,
            reward_service,
            talent_matrix_entry_service,
            ext,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PerformanceModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
