//! Use case type aliases for Appraisal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAppraisalDto, UpdateAppraisalDto};
use crate::application::service::AppraisalService;
use crate::domain::entity::Appraisal;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAppraisalUseCase = CreateUseCase<Appraisal, CreateAppraisalDto, AppraisalService>;
pub type UpdateAppraisalUseCase = UpdateUseCase<Appraisal, UpdateAppraisalDto, AppraisalService>;
pub type GetAppraisalUseCase    = GetUseCase<Appraisal, AppraisalService>;
pub type DeleteAppraisalUseCase = DeleteUseCase<Appraisal, AppraisalService>;
pub type ListAppraisalUseCase   = ListUseCase<Appraisal, AppraisalService>;

// <<< CUSTOM
// END CUSTOM
