//! Use case type aliases for AppraisalCycle aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAppraisalCycleDto, UpdateAppraisalCycleDto};
use crate::application::service::AppraisalCycleService;
use crate::domain::entity::AppraisalCycle;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAppraisalCycleUseCase = CreateUseCase<AppraisalCycle, CreateAppraisalCycleDto, AppraisalCycleService>;
pub type UpdateAppraisalCycleUseCase = UpdateUseCase<AppraisalCycle, UpdateAppraisalCycleDto, AppraisalCycleService>;
pub type GetAppraisalCycleUseCase    = GetUseCase<AppraisalCycle, AppraisalCycleService>;
pub type DeleteAppraisalCycleUseCase = DeleteUseCase<AppraisalCycle, AppraisalCycleService>;
pub type ListAppraisalCycleUseCase   = ListUseCase<AppraisalCycle, AppraisalCycleService>;

// <<< CUSTOM
// END CUSTOM
