//! Use case type aliases for Feedback aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFeedbackDto, UpdateFeedbackDto};
use crate::application::service::FeedbackService;
use crate::domain::entity::Feedback;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFeedbackUseCase = CreateUseCase<Feedback, CreateFeedbackDto, FeedbackService>;
pub type UpdateFeedbackUseCase = UpdateUseCase<Feedback, UpdateFeedbackDto, FeedbackService>;
pub type GetFeedbackUseCase    = GetUseCase<Feedback, FeedbackService>;
pub type DeleteFeedbackUseCase = DeleteUseCase<Feedback, FeedbackService>;
pub type ListFeedbackUseCase   = ListUseCase<Feedback, FeedbackService>;

// <<< CUSTOM
// END CUSTOM
