//! Use case type aliases for Goal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateGoalDto, UpdateGoalDto};
use crate::application::service::GoalService;
use crate::domain::entity::Goal;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateGoalUseCase = CreateUseCase<Goal, CreateGoalDto, GoalService>;
pub type UpdateGoalUseCase = UpdateUseCase<Goal, UpdateGoalDto, GoalService>;
pub type GetGoalUseCase    = GetUseCase<Goal, GoalService>;
pub type DeleteGoalUseCase = DeleteUseCase<Goal, GoalService>;
pub type ListGoalUseCase   = ListUseCase<Goal, GoalService>;

// <<< CUSTOM
// END CUSTOM
