//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod appraisal_usecases;
pub mod appraisal_cycle_usecases;
pub mod feedback_usecases;
pub mod goal_usecases;
pub mod reward_usecases;
pub mod talent_matrix_entry_usecases;

pub use appraisal_usecases::{
    CreateAppraisalUseCase, UpdateAppraisalUseCase, GetAppraisalUseCase,
    DeleteAppraisalUseCase, ListAppraisalUseCase,
};
pub use appraisal_cycle_usecases::{
    CreateAppraisalCycleUseCase, UpdateAppraisalCycleUseCase, GetAppraisalCycleUseCase,
    DeleteAppraisalCycleUseCase, ListAppraisalCycleUseCase,
};
pub use feedback_usecases::{
    CreateFeedbackUseCase, UpdateFeedbackUseCase, GetFeedbackUseCase,
    DeleteFeedbackUseCase, ListFeedbackUseCase,
};
pub use goal_usecases::{
    CreateGoalUseCase, UpdateGoalUseCase, GetGoalUseCase,
    DeleteGoalUseCase, ListGoalUseCase,
};
pub use reward_usecases::{
    CreateRewardUseCase, UpdateRewardUseCase, GetRewardUseCase,
    DeleteRewardUseCase, ListRewardUseCase,
};
pub use talent_matrix_entry_usecases::{
    CreateTalentMatrixEntryUseCase, UpdateTalentMatrixEntryUseCase, GetTalentMatrixEntryUseCase,
    DeleteTalentMatrixEntryUseCase, ListTalentMatrixEntryUseCase,
};

// <<< CUSTOM
// END CUSTOM
