//! Use case type aliases for Reward aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateRewardDto, UpdateRewardDto};
use crate::application::service::RewardService;
use crate::domain::entity::Reward;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateRewardUseCase = CreateUseCase<Reward, CreateRewardDto, RewardService>;
pub type UpdateRewardUseCase = UpdateUseCase<Reward, UpdateRewardDto, RewardService>;
pub type GetRewardUseCase    = GetUseCase<Reward, RewardService>;
pub type DeleteRewardUseCase = DeleteUseCase<Reward, RewardService>;
pub type ListRewardUseCase   = ListUseCase<Reward, RewardService>;

// <<< CUSTOM
// END CUSTOM
