//! Use case type aliases for TalentMatrixEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTalentMatrixEntryDto, UpdateTalentMatrixEntryDto};
use crate::application::service::TalentMatrixEntryService;
use crate::domain::entity::TalentMatrixEntry;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTalentMatrixEntryUseCase = CreateUseCase<TalentMatrixEntry, CreateTalentMatrixEntryDto, TalentMatrixEntryService>;
pub type UpdateTalentMatrixEntryUseCase = UpdateUseCase<TalentMatrixEntry, UpdateTalentMatrixEntryDto, TalentMatrixEntryService>;
pub type GetTalentMatrixEntryUseCase    = GetUseCase<TalentMatrixEntry, TalentMatrixEntryService>;
pub type DeleteTalentMatrixEntryUseCase = DeleteUseCase<TalentMatrixEntry, TalentMatrixEntryService>;
pub type ListTalentMatrixEntryUseCase   = ListUseCase<TalentMatrixEntry, TalentMatrixEntryService>;

// <<< CUSTOM
// END CUSTOM
